- web/app/components/auth-panel/auth-panel.jsx
- web/app/components/blocked-users/blocked-users.jsx
- web/app/components/comment/comment.jsx
- web/app/components/comment/comment.scss
- web/app/components/input/input.jsx
- web/app/components/root/root.jsx
- web/app/components/thread/thread.jsx
I've added basic ARIA mark-up for links and buttons.
The only thing I'm doubtful about is how to organize threads and replies. I experimented a bit, but this functionality needs to be tested and might be reverted in future.
I also didn't mark up user name links that toggle user IDs: I might implement it in future, but it needs also a description, otherwise a blind user won't understand what the click on a user name does.
> Add basic ARIA mark-up

- web/app/components/root/root.jsx
- web/iframe.html
Two changes:
* doing requests in parallel on first load
* showing bouncer before js bundle is loaded
First load on slow internet is pretty slow, and also blank screen while it loading js bundle doesn't help, so decided to improve that.
Also have an idea to load comments before we actually loaded iframe and pass a message inside iframe on load, but this is more complicated change, its better to split them, so probably next PR (if tests will show that it makes sense)
> Improved first load time and UX on first load

- .travis.yml
> Add basic Travis CI configuration.

- Dockerfile
https://golang.org/doc/go1.9#vendor-dotdotdot
> No need to explicitly exclude vendor with Go 1.9+.

- .travis.yml
- Dockerfile
- README.md
- app/main.go
- app/rest/api/admin.go
- app/rest/api/admin_test.go
- app/rest/api/import.go
- app/rest/api/migrator.go
- app/rest/api/migrator_test.go
- app/rest/api/rest.go
- app/rest/api/rest_test.go
- app/rest/api/rss_test.go
- app/rest/httperrors.go
- app/rest/httperrors_test.go
- app/rest/proxy/image_test.go
- app/rest/tree.go
- app/rest/tree_test.go
- app/store/comment.go
- app/store/engine/bolt_accessor.go
- app/store/engine/bolt_accessor_test.go
- app/store/engine/bolt_admin.go
- app/store/engine/bolt_admin_test.go
- app/store/engine/engine.go
- remark.rest
- scripts/create-backup.sh
- scripts/migrate-data.sh
- scripts/restore-backup.sh
backend changes for #55 
- new parameter `READONLY_AGE`, default 0 (disabled)
- change `count` bucket to more generic `info` and here post info
- extend post info with first & last ts for the post
- add new bucket `readonly` to keep posts manually marked as ro
- add new rest method to set/reset read-only
- add new rest method to get post info
- create method rejects attempts to modify RO post
_This change requires storage migration._
> feature/ts - read-only support 

- app/rest/api/rss_test.go
- app/store/engine/bolt_accessor_test.go
- app/store/engine/bolt_admin.go
> lint: misspell, ineffassign

- app/rest/auth/provider.go
- app/rest/auth/providers.go
- app/rest/auth/providers_test.go
I checked out the github API response for user profile. If user left his profile name empty, `"user": null` returns in the response. When go's `json.Unmarshal` decodes json `null` value it converts it to `nil`. So I refactored method `value()` of `userData` struct in `remark/app/rest/auth/provider.go` to avoid checking string `"<nil>"` in github provider.
(from PR #64)
> refactor Github OAuth provider

- Gopkg.lock
- README.md
- app/main.go
- app/main_test.go
- app/rest/auth/providers.go
- app/rest/auth/providers_test.go
- vendor/golang.org/x/oauth2/yandex/yandex.go
- web/app/common/constants.js
I added the Yandex OAuth provider, altered the UI and documentation, added unit-tests and check the Yandex login flow manually.
The list of permissions has *Access to user avatar* and *Access to username, first name and surname, gender*. The latter is needed to get a friendly username. In fact a yandex user can have 3 different names:
* `login` – same as first part of email address, this one is always required,
* `real_name` – the combination of First and Last names, optional,
* `display_name` – the name is used for displaying user name in yandex services, this name is visible to other yandex users.
So more preferable name for us is `display_name`. If it's empty we use `real name`, otherwise `login`.
The doc is here: https://tech.yandex.com/passport/doc/dg/reference/response-docpage/#norig …
> add Yandex OAuth provider #34

- backend/app/rest/api/middleware_test.go
Small change: a forgotten `defer body.Close()` in a test
> Add defer body closing in a test

- web/app/components/comment/__time/comment__time.scss
- web/app/components/comment/__username/comment__username.scss
> Fix right margin for verified user icon

- backend/app/rest/api/rss.go
- backend/app/rest/api/rss_test.go
Added `/rss/reply?user=userID&site=siteID` endpoint. It retrieves last 100 comments for site `siteID` and for each comment reads parent to determine is it reply to `userID` or not. Stops iterate when max replies are found or comment were published later than 30 minutes. Skips replies when user replies to himself.
relates to #111
> RSS replies to a user #111

- web/app/components/thread/collapsedCommentsMiddleware.js
- web/app/components/thread/getCollapsedComments.js
- web/app/components/thread/index.js
- web/app/components/thread/saveCollapsedComments.js
- web/app/components/thread/thread.actions.js
- web/app/components/thread/thread.getters.js
- web/app/components/thread/thread.jsx
- web/app/components/thread/thread.reducers.js
- web/app/components/thread/thread.reducers.test.js
- web/app/remark.js
- web/app/store.js
- web/package.json
- web/yarn-error.log
Here is a very basic integration with redux. I've moved all the complex logic from the Thread component to the reducer, which is also responsible for restoring the initial state from the local storage. Reducer is already covered with a couple of specs, would be also useful to have a spec for getters. Related to #95 and #96
> Basic redux integration for thread component

- web/app/components/input/input.jsx
- web/app/components/input/textarea-autosize.jsx
Reactor Input component into a controlled component, this fixes #169 
And moved auto-size behavior into a separate component to reduce the complexity of Input component.
> Input fix for Edge issue 169

- backend/app/rest/api/admin_test.go
- backend/app/rest/api/rest_private_test.go
- backend/app/rest/api/rest_public_test.go
- backend/app/rest/api/rest_test.go
- backend/app/rest/api/rss_test.go
Windows fs can't remove testDb until file still used.
Therefore we need to close datastore on cleanup.
> Close DataStore on cleanup in tests

- backend/app/migrator/disqus.go
- backend/app/migrator/wordpress.go
- backend/app/migrator/wordpress_test.go
for #156 
WP importer starts to use CommentFormatter to convert content in common way as remark does when saves comments.
Fix previous PR #188 (I did git rebase master && git push --force but nothing happen in PR)
> Use comment formatter for wp importer

- web/app/components/user-info/user-info.jsx
- web/app/embed.js
What is going on here? To make close by Esc reliable we also need to add a `keydown` event listener to the iframe, because events do not propagate out of an iframe to a parent. Originally adding `keydown` event listener was done via a `contentDocument` property of the iframe, but the browser does not allow to access `contentDocument` if the origin of the iframe is different from the parent. Now I change it so that UserInfo component used `window.parent.postMessage` to send a message when escape is pressed. This should work reliably.
> UserInfo close by Esc fix, issue #187 

- web/app/common/api.js
- web/app/components/comment/__action/_type/_delete/comment__action_type_delete.scss
- web/app/components/comment/__edit-timer/comment__edit-timer.scss
- web/app/components/comment/comment.jsx
- web/app/components/comment/index.js
As a continuation of #200 
This pull request adds delete user's own comment button while in edit time range.
Behaviour similar to admin's delete comment button.
> frontend: delete own comment button added

- web/app/common/constants.js
- web/app/common/localStorage.js
- web/app/components/auth-panel/auth-panel.jsx
- web/app/components/thread/getCollapsedComments.js
- web/app/components/thread/saveCollapsedComments.js
- web/comments.ejs
- web/webpack.config.js
Related to #218 
When using Firefox with "block third-party cookies: all" setting, the comments iframe fails with "the operation is insecure" error message.
Crash caused by call of any method of localStorage.
Current pr adds check if storage available and if not shows placeholder below instead of "Sign in with..."
By clicking on a "new page" user relocated to new page with the same origin as an iframe (template is  `/web/comments.ejs`)
If user blocked cookies completely placeholder will be the following
Current solution was tested mainly with Firefox, Safari seems to allow cookies even with "Prevent cross-site tracking" turned on.
> third party cookies blocked fallback

- backend/app/rest/api/rest_test.go
- backend/app/store/service/service.go
- backend/app/store/service/service_test.go
Hello.
Messed up a little with #207 yesterday.
Now it is truly possible to disable voting by setting vote limit to zero.
> fixed zero vote limit not respected and treated as unlimited

- web/app/components/comment/_useless/comment_useless.scss
Let's show useless comments when user hovers them.
> Reset opacity for useless comment by mouse hover event

- backend/app/cmd/cmd.go
I propose to simplify makeDirs() function.
(Note that current implementation of makeDirs() contains a bug on the line 124 - it does not wrap right error variable. It also does not check whether existed path is a directory.)
> simplify makeDirs()

- web/app/components/comment/comment.jsx
Rel to #230 
PR disables comments voting on read-only posts.
@umputun I made it by just disabling arrows, did you mean to completely hide them?
> Disable voting on read-only posts

- backend/app/notify/telegram_test.go
Hi! I've just tried to increase test coverage for Telegram part
Before it was
`coverage: 86.7% of statements`
After new test cases it has become
`coverage: 90.0% of statements`
Please check my changes
> Telegram increase coverage

- backend/app/notify/telegram.go
As proposed in #255 , following changes will improve versatility of a Telegram integration, thus allowing users to have a private source of notifications. 
I'm not that confident with Go, so this PR have following drawback:
- I was not able to provide test-case to cover refactored functions
- Refactored function may check the value of a `channelID` argument,  and append `@` in case it contains non-numeric literals
> Remove prefixing of a `@` character to the channel name

- Dockerfile
`.git` folder isn't present in tarballs pulled from releases, e.g. `wget https://github.com/umputun/remark/archive/v.1.2.1.tar.gz`, and not used during the build anyways
> do not add .git folder to a build layer

- web/app/components/comment/comment.jsx
- web/app/utils/debounce.js
https://github.com/umputun/remark/issues/148
We need to have onBlur and onChange events listeners for the select for the "block user" as it advised by es-lint. But if we simply add onBlur event listener it will cause infinite loop of blur -> confirm pop-up -> cancel -> blur -> confirm pop-up... So we have to debounce the events to process them only one time.
> Fix block users select behavior

- backend/app/rest/httperrors.go
- web/app/components/comment/__vote/comment__vote.scss
- web/app/components/comment/comment.jsx
- web/app/components/input/input.jsx
- web/app/utils/errorUtils.js
Issue https://github.com/umputun/remark/issues/256
- Adds common function to get error message from the http response
- Adds error message for the voting request failure displayed under the voting buttons
- Adds restoring of voting data after voting request failed
Example of the error message:
Handling error when user has been blocked:
> Hanlde limiter rejection on UI side

- README.md
- web/app/components/auth-panel/auth-panel.jsx
- web/app/components/comment/comment.jsx
Issue https://github.com/umputun/remark/issues/274
* show the value of `controversy` in the hover on scores: value if it exists,
"No controversy." if value is zero, "No votes yet." if there are no votes.
* add a new sorting mode "controversial" to "sort by" dropdown
> Add "contradiction index" metric

- web/app/common/api.ts
- web/app/common/fetcher.ts
- web/app/components/comment/comment.tsx
- web/app/components/comment/connected-comment.ts
- web/app/store/thread/actions.ts
- web/app/store/thread/reducers.test.ts
- web/app/testUtils/index.ts
- web/jest.config.js
- web/setup-jest-env.js
- web/tsconfig.json
* fix for #310 
There is a thing. Comment below critical score being unfolded does not saves its collapse state in local storage, and with page reload will be collapsed again. This is because collapsed comments stored as plain list, and if comment is in it, then it collapsed. Useless comment being unfolded just doesn't save any thing to local storage. I don't know, should I fix it, or let we assume that this is "by design"?
Fix will be to store not in list, but in `map[comment id]boolean`.
> Fix useless comment collapse

- web/.eslintrc.js
- web/app/@types/__webpack_public_path__.d.ts
- web/app/counter.ts
- web/app/deleteme.ts
- web/app/embed.ts
- web/app/last-comments.tsx
- web/app/remark.tsx
- web/webpack.config.js
Add ie11 support (though I'm not sure 100%)
One additional quirk from ie11 is that it caches xhr requests, so no-cache headers should be added to backend
```
Cache-control: no-cache
Cache-control: no-store
Pragma: no-cache
Expires: 0
```
> Restore ie11 support

- web/app/components/comment/_editing/comment_editing.scss
- web/app/components/comment/_replying/comment_replying.scss
> Fix comment input top margin in editing or replying mode

- README.md
- backend/app/cmd/server.go
- backend/app/rest/api/rest.go
- backend/app/rest/api/rest_public.go
- backend/app/rest/api/rest_public_test.go
This one adds API to stream minimal updates for a given post. The goal is to provide UI with a way to subscribe to such update events and be able to refresh or notify the user (see #253)
The API is `/stream/info` and it allows smth like this:
```
curl -n "http://127.0.0.1:8080/api/v1/stream/info?site=remark&url=https://remark42.com/demo/"
{"url":"https://remark42.com/demo/","count":19,"first_time":"2018-09-02T13:27:48.680420472-05:00","last_time":"2019-05-12T13:11:50.548327608-05:00"}
{"url":"https://remark42.com/demo/","count":20,"first_time":"2018-09-02T13:27:48.680420472-05:00","last_time":"2019-06-02T15:29:27.799347624-05:00"}
{"url":"https://remark42.com/demo/","count":21,"first_time":"2018-09-02T13:27:48.680420472-05:00","last_time":"2019-06-02T15:29:50.941572771-05:00"} …
```
> Info stream

- README.md
Hello there!
In effort fixing #351 I've checked through all configuration options of the server and found that only two of them are missing. I have added them and also fixed one typo and wrong case for Disqus and Wordpress.
> Add missing configuration options to readme (fix #351)

- frontend/app/common/api.ts
- frontend/app/store/user/actions.ts
When user is logged in, has no blocked users, and tries to open settings widget operation fails because reducer expects array of blocked users but api (`/admin/blocked`) returns null
> Fix: settings widget fails because it expects list but gets null

- frontend/app/components/comment/_level/comment_level.scss
- frontend/app/components/comment/_theme/_dark/comment_theme_dark.scss
- frontend/app/components/comment/_theme/_light/comment_theme_light.scss
- frontend/app/components/comment/comment.scss
https://github.com/radio-t/radio-t-site/issues/94
@Reeywhaar
> show threads

- frontend/app/components/settings/settings.tsx
wrong className leads to unstyled button in settings
before:
after:
> Fix wrong classname

- frontend/app/store/sort/actions.ts
Sorting change appears broken because cookie path being set for "/web" but after refresh takes value from cookie with path `/web/`.
> Fix sort been stalled

- frontend/app/components/comment/comment.tsx
- frontend/app/components/comment/connected-comment.ts
To https://github.com/umputun/remark/issues/377#issuecomment-513491892
Now blocked comments rendered like on screenshot below, no matter whether user is admin or not:
One thing I'm not sure is that if user was blocked permanently his comment (if it has childs) will be rendered like this:
... so user traces still present. @umputun if you think this is undesired, I can tell that I'm actually cannot differentiate if user was blocked permanently or not on front, so to render such comment differently (ghosted avatar and so on) I need another one field in User struct.
> Fix blocking

- frontend/app/common/config-types.ts
- frontend/app/embed.ts
This might not be essential for many people but it seems like a simple change and it seems sensible to allow people to change it; e.g. to follow their desired naming conventions.
This also introduces the additional possibility of having multiple sets of comments on one page (as long as different URL values are provided) – I want to use remark on a site for online consultation, with users able to comment on multiple sections of a proposal.
If there are repercussions of this change I've missed then apologies!
> Allow ID of container node to optionally be provided in comments widget config

- README.md
Here is the screenshot of rendered README.md on https://github.com/umputun/remark :
After this change `Version` will be alinged.
> Fixing indent in README.md

- .github/workflows/blank.yml
- .travis.yml
- Dockerfile
- Add support Github Actions (copy build docker image from `.travis.yml`)
- For correct work with coveralls.io in secrets should setted `COVERALLS_TOKEN`
> Use GitHub actions as ci

- Dockerfile
- compose-dev-backend.yml
On some cases `docker-compose -f compose-dev-backend.yml build` may fail due to timeout.
This PR add ability to increase timeout on local machines e. g.
`BACKEND_TEST_TIMEOUT="1m" docker-compose -f compose-dev-backend.yml build`
> Add parameter to change backend test timeout

- backend/app/cmd/server.go
- backend/app/store/image/bolt_store.go
- backend/app/store/image/bolt_store_test.go
- backend/app/store/image/fs_store.go
- backend/app/store/image/fs_store_test.go
- backend/app/store/image/image.go
Add bolt image store support #445 
Implementation stores staging in separate bucket and copy data to main bucket on commit.
Data from staged not deleted immediately, it would be removed on cleanup.
All comments will be very appreciated.
> Add bolt image storage

- .github/workflows/ci-build.yml
Attempt to fix #462 using [GITHUB_TOKEN](https://help.github.com/en/github/automating-your-workflow-with-github-actions/authenticating-with-the-github_token#about-the-github_token-secret) which is not a standard secret and would work in forks.
> Change coveralls to use build-in GITHUB_TOKEN

- backend/app/notify/notify.go
- backend/app/notify/notify_test.go
- backend/app/notify/telegram.go
- backend/app/notify/telegram_test.go
- backend/app/rest/api/rest_private.go
This change is necessary if we want to send more than just `store.Comment` (let's say user email or verification token) trough the `notify.Submit`.
Added as separate PR as `notify.Submit` triggers changes in many parts like `notify.Terraform` and will clutter `notify.Email` PR which I'm working on.
Change affects internal programming interface but nothing frontend-facing will be altered.
> Switch notify.Submit to receive notify.Request instead of store.Comment

- .github/workflows/ci-build.yml
- Makefile
- README.md
- backend/_example/memory_store/accessor/data.go
- backend/app/main_test.go
- backend/app/notify/telegram.go
- backend/app/rest/api/rest_test.go
- enable `golangci-lint run` for memory_store example
- fix detected errors in `memory_store`:
```
accessor/data.go:409:3  ineffassign  ineffectual assignment to `meta`
accessor/data.go:419:3  ineffassign  ineffectual assignment to `meta`
```
- fix runaway goroutine in `TestRest_Shutdown`
- add `race_test` option to Makefile
- fix multiple typos across the code
> Multiple CI and code fixes

- README.md
> README.md: fix a typo in a variable name from an example

- README.md
- compose-dev-backend.yml
- compose-dev-frontend.yml
- docker-compose.yml
- frontend/Readme.md
- format all docker-compose files with the same settings (indent 4)
- remove outdated mongo reference from backend docker-compose comments
- unify comment format at the beginning of frontend and backend  docker-compose
- fix reference to frontend readme file to proper case
- fix single typo in frontend readme
> docker-compose format and comment fixes

- backend/app/cmd/server.go
- backend/app/rest/api/rest.go
- backend/app/rest/api/rest_private.go
- backend/app/rest/api/rest_private_test.go
- backend/app/rest/httperrors.go
- backend/app/rest/httperrors_test.go
Attempt to fix #495.
I've moved unsubscribe email endpoint outside of API endpoints space because API already has `DELETE /api/v1/email` endpoint for this purpose.
Images of normal message and errors in this PR implementation:
> Move email unsubscription endpoint outside of API and make it HTML

- backend/_example/memory_store/accessor/data_test.go
- backend/app/cmd/cleanup_test.go
- backend/app/cmd/cmd_test.go
- backend/app/cmd/import_test.go
- backend/app/cmd/remap_test.go
- backend/app/cmd/restore_test.go
- backend/app/cmd/server_test.go
- backend/app/migrator/backup_test.go
- backend/app/migrator/disqus_test.go
- backend/app/migrator/mapper_test.go
- backend/app/migrator/migrator_test.go
- backend/app/migrator/native_test.go
- backend/app/migrator/wordpress_test.go
- backend/app/notify/telegram_test.go
- backend/app/rest/api/admin_test.go
- backend/app/rest/api/migrator_test.go
- backend/app/rest/api/rest_private_test.go
- backend/app/rest/api/rest_public_test.go
- backend/app/rest/api/rest_test.go
- backend/app/rest/api/ssl_test.go
- backend/app/rest/proxy/image_test.go
- backend/app/rest/user_test.go
- backend/app/store/engine/bolt_test.go
- backend/app/store/engine/remote_test.go
- backend/app/store/image/bolt_store_test.go
- backend/app/store/image/fs_store_test.go
- backend/app/store/image/image_test.go
- backend/app/store/service/service_test.go
This PR change clarifies test failure error messages for `err` checks in all tests across the code.
Current behavior on test failure:
```
--- FAIL: TestFsStore_Cleanup (0.50s)
fs_store_test.go:273: 
Error Trace:	fs_store_test.go:273
Error:      	Expected value not to be nil.
Test:       	TestFsStore_Cleanup
Messages:   	no dir /dir_name on staging anymore
```
After this PR:
```
--- FAIL: TestFsStore_Cleanup (0.53s)
fs_store_test.go:273: 
Error Trace:	fs_store_test.go:273
Error:      	An error is expected but got nil.
Test:       	TestFsStore_Cleanup
Messages:   	no dir /dir_name on staging anymore
```
List of replacements I've applied:
```
require.Nil(t, err -> require.NoError(t, err
require.NotNil(t, err -> require.Error(t, err
assert.Nil(t, err -> assert.NoError(t, err
assert.NotNil(t, …
```
> Replace "(Not)Nil" test checks for errors with with "(No)Error"

- backend/app/store/image/fs_store_test.go
$subj, at least 8 false poisitives in last six months detected in #380.
> fix flapping TestFsStore_Cleanup

- backend/_example/memory_store/server/rpc_test.go
Fix attached list of tests false positive failures which are caused by HTTP server which is returned to test without properly checking if it's ready or not.
| [TestRPC_admEnabledHndl](https://github.com/umputun/remark/blob/aafe760bafb89ed4e939ecbb091d2c71ae000b6a/backend/_example/memory_store/server/rpc_test.go#L350) | [Nov 22](https://github.com/umputun/remark/commit/aafe760bafb89ed4e939ecbb091d2c71ae000b6a/checks?check_suite_id=323640436#step:5:117) |
| [TestRPC_admEventHndl](https://github.com/umputun/remark/blob/bc1893883b6880655bae8572e753884104ebebc6/backend/_example/memory_store/server/rpc_test.go#L364) | [Dec 8](https://github.com/umputun/remark/commit/bc1893883b6880655bae8572e753884104ebebc6/checks?check_suite_id=348041164# …
> make TestRPC tests reliably wait for HTTP server to start

- backend/_example/memory_store/server/rpc_test.go
Recently merged #505 didn't fix the attached list of tests false positive failures, which is clear from the fact that last error fired (what a luck!) on the last commit to PR branch (but in my repo, not in this one). 
The previous PR fixed the problem which is yet unseen on the SSD-disk-based setup I have locally and GitHub Actions seems to have. The real problem is within this log entry:
INFO  listen tcp :43300: bind: address already in use
This PR tackles this problem. The solution is purely theoretical, as I can not reproduce the problem locally, unfortunately.
| [TestRPC_admEnabledHndl](https://github.com/umputun/remark/blob/aafe760bafb89ed4e939ecbb091d2c71ae000b6a/backend/_example/memory_store/server/rpc_test.go#L350) | [Nov …
> Check if the port already in use in TestRPC_ tests server startup

- backend/_example/memory_store/server/rpc_test.go
- backend/app/cmd/cleanup.go
- backend/app/cmd/server_test.go
- backend/app/rest/api/rest_test.go
This PR might prevent failures like following (first 4 failures root cause is not clear):
| [TestServerApp](https://github.com/umputun/remark/blob/cdc1ae1e85d6efe5f0bbf341df71a77bfe09cd2e/backend/app/cmd/server_test.go#L25) | [Oct 14](https://github.com/umputun/remark/commit/8315299676961cf00de10d45923d5e318d12e484/checks?check_suite_id=264658757#step:5:244) |
| [TestServerApp](https://github.com/umputun/remark/blob/cdc1ae1e85d6efe5f0bbf341df71a77bfe09cd2e/backend/app/cmd/server_test.go#L25) | [Oct 16](https://github.com/umputun/remark/commit/3e4f9d6f02a6c8b204354f781c8b7d2c1a7d3941/checks?check_suite_id=266861491#step:5:244) |
| [TestServerApp](https://github.com/umputun/remark/blob/ee63763120b5daf05e52402d720ceeb808c5fee7/backend/ …
> Improve TestServer* tests reliability

- backend/app/cmd/server_test.go
- backend/app/main_test.go
Fix following failures potentially:
| [Test_Main](https://github.com/umputun/remark/blob/cb60261124a7648fe2ae735e78833ff0dff54d4c/backend/app/main_test.go#L21) | [Oct 18](https://github.com/umputun/remark/commit/cb60261124a7648fe2ae735e78833ff0dff54d4c/checks?check_suite_id=271350649#step:5:210) |
| [Test_Main](https://github.com/umputun/remark/blob/f859239bdf9ac8d72b6a6bb2368764e720c822d8/backend/app/main_test.go#L21) | [Oct 29](https://github.com/umputun/remark/commit/f859239bdf9ac8d72b6a6bb2368764e720c822d8/checks?check_suite_id=285601644#step:5:214) |
| [Test_Main](https://github.com/umputun/remark/blob/c273828647e32aea21622eb0c4b7be02c3d6de19/backend/app/main_test.go#L21) | [Oct …
> Improve Test_Main reliability

- backend/_example/memory_store/accessor/data_test.go
- backend/app/cmd/backup_test.go
- backend/app/cmd/server_test.go
- backend/app/main_test.go
- backend/app/notify/email_test.go
- backend/app/notify/telegram_test.go
- backend/app/rest/api/admin_test.go
- backend/app/rest/api/rest_private_test.go
- backend/app/rest/api/rest_public_test.go
- backend/app/rest/api/rest_test.go
- backend/app/rest/httperrors_test.go
- backend/app/store/service/service_test.go
- backend/app/store/service/title_test.go
- backend/app/store/service/tree_test.go
- Finish work started in #503: all errors across all tests now handled via `assert.(No)Error` instead of `(Not)Nil`.
- Improve reliability of tests with following historical false positives:
| [TestRest_InfoStreamCancel](https://github.com/umputun/remark/blob/cfdcc4fffda53f0b50e6e636e70ce1fdd00f7c63/backend/app/rest/api/rest_public_test.go#L630) | [Oct 19](https://github.com/umputun/remark/commit/cfdcc4fffda53f0b50e6e636e70ce1fdd00f7c63/checks?check_suite_id=272475230#step:5:482) |
| [TestRest_InfoStreamCancel](https://github.com/umputun/remark/blob/1cbedb85b06b86c09f36d0b3625a210f6d54569c/backend/app/rest/api/rest_public_test.go#L630) | [Oct 19](https://github.com/umputun/remark/runs/266884368#step:5:482) |
| …
> Fixes for multiple tests

- backend/app/cmd/server_test.go
- backend/app/main_test.go
- backend/app/rest/api/rest_public_test.go
$subj, `<-done` position was wrong in multiple locations in `rest_public_test.go`. 6 test runs of GitHub Actions I've conducted haven't shown any problems after this PR.
> Fix flapping TestRest_ tests

- backend/app/cmd/server.go
- backend/app/rest/api/rest.go
Necessary to enable email notifications UI in #496 (as without this PR there is no way to know if email notifications are enabled or not).
> Expose email_notifications flag on /config endpoint

- frontend/app/components/dropdown/dropdown.tsx
I fixed this error which was mentioned in this #490 
```
/remark/frontend/app/components/dropdown/dropdown.tsx(109,7)
TS2322: Type 'string | null' is not assignable to type 'string'.
Type 'null' is not assignable to type 'string'.
```
> Fix typescript error that might be caused under windows

- backend/app/store/service/title_test.go
Сame across some unclosed test servers and fixed it. It wasn't done on purpose, is it?
> Shutdown test servers

- .github/workflows/ci-build.yml
- backend/app/cmd/server_test.go
- potentially make TestServerApp_MainSignal more robust (next time I'll tear all "should be finished within X seconds" away from test code);
- rename last build step to `build docker image with frontend tests` because that's what it is.
> Fix TestServerApp_MainSignal

- compose-dev-frontend.yml
- frontend/app/common/static_store.ts
- frontend/app/common/types.ts
- frontend/app/components/comment/_editing/comment_editing.scss
- frontend/app/components/comment/_replying/comment_replying.scss
- frontend/app/components/comment/comment.tsx
- frontend/app/components/input/_simple/input_simple.scss
- frontend/app/components/input/input.test.tsx
- frontend/app/components/input/input.tsx
- frontend/app/components/input/styles.ts
- frontend/app/components/root/root.tsx
- frontend/app/testUtils/index.ts
- frontend/package.json
It just hide elements from view when `simple_view` received from server.
Resolving #474
> Add "simple view" mode

- .github/workflows/ci-build.yml
- .github/workflows/ci-test-backend.yml
- .github/workflows/ci-test-frontend.yml
- Dockerfile
Fix #521.
Separates the CI pipeline into the build, test for backend, and test for frontend. Also, introduce conditional build, so backend won't be tested on frontend changes.
Results of the change can be observed [here](https://github.com/paskal/remark/commits/ci_test_branch) after `separate build and test CI workflow, separate frontend and backend tests` commit.
> [CI] Separate tests and build, frontend and backend tests

- README.md
- backend/app/cmd/server.go
- Fixed "Improve quality of images #488" (sharp vibrant awesome images)
- Added retina display support
- Support for 3x devices including 11 Pro and MacPro
- Resources usage is good as was for scaled images (change is subtle after scaling), example for big image is 180 KB and 298 KB.
> Fixed "Improve quality of images #488" (sharp vibrant awesome images)

- frontend/app/components/input/textarea-autosize.tsx
This issue was closed https://github.com/developit/preact/issues/326 and now we can pass value right to textarea `value` attribute.
It should fix #484 issue.
> Fix right-to-left typing in IE11/Edge

- backend/app/cmd/server.go
- backend/app/notify/email.go
- backend/app/notify/notify.go
- backend/app/notify/notify_test.go
- backend/app/rest/api/rest_private.go
- backend/app/rest/api/rest_private_test.go
- backend/app/store/service/service.go
- backend/app/store/service/service_test.go
- backend/app/store/user.go
Change for #496, add EmailSubscription flag only for `GET /user` endpoint response to use in UI.
Also, refactor `DataStore` methods which use only `SiteID` part of `store.Locator` to use only `SiteID` instead of the `Locator` object.
> Add email subscription info to User information

- .github/workflows/ci-test-frontend.yml
I realized that now we run frontend build twice in test job and for the third time we run it in docker.
I removed all that runs from test job.
> Remove build of frontend from test job

- frontend/app/components/auth-panel/auth-panel.test.tsx
- frontend/app/components/auth-panel/auth-panel.tsx
One of the improvements from #426 
I changed all "sign in/out" texts to "login/out" for consistency.
And now it always "login" in prev version it has long/short text for open/blocked post.
> Change text "sign in" to "login"

- backend/app/notify/email.go
- backend/app/notify/email_test.go
$subj, bug discovered during #537 tests: user I've used for test got email notification for reply to his own comment.
> check user equality for email notifications only by ID instead of complete object

- backend/app/rest/api/admin.go
- backend/app/rest/api/admin_test.go
$subj, discovered after I found out that /deleteme is not available for anonymous users and wanted to check if it's properly working for normal ones.
> Delete user email on /deleteme request

- frontend/app/common/static_store.ts
- frontend/app/common/types.ts
- frontend/app/components/comment/comment.test.tsx
- frontend/app/components/comment/comment.tsx
- frontend/app/testUtils/index.ts
> Allow voting for anonymous users

- frontend/app/components/root/__show-more/root__show-more.scss
It was aligned by the left side.
This button visible only on mobile version.
> Fix position of "show more" button

- README.md
- backend/app/cmd/cmd.go
- backend/app/cmd/server.go
- backend/app/cmd/server_test.go
- backend/app/main.go
- compose-dev-backend.yml
- Move SMTP settings to separate section and create new "Deprecated parameters" section in the Readme.
- Set new options from deprecated ones and print warnings about their usage in the log, example for all current variables:
```
2020/01/14 21:21:15.204 [WARN]  --auth.email.host is deprecated and will be removed in v1.7.0, please use --smtp.host instead
2020/01/14 21:21:15.204 [WARN]  --auth.email.port is deprecated and will be removed in v1.7.0, please use --smtp.port instead
2020/01/14 21:21:15.204 [WARN]  --auth.email.tls is deprecated and will be removed in v1.7.0, please use --smtp.tls instead
2020/01/14 21:21:15.204 [WARN]  --auth.email.user is deprecated and will be removed in v1.7.0, please use --smtp.username instead
2020/01/14 21:21:15.204 [WARN]  --auth.email.passwd is …
```
> Unify SMTP settings in separate section

- frontend/app/components/comment/_replying/comment_replying.scss
- frontend/app/components/comment/comment.scss
- frontend/app/components/thread/__collapse/thread__collapse.scss
1. If you open this link you can see that avatars on previous comments are hidden, and free space under comments appeared.
https://radio-t.com/p/2020/01/07/prep-684/#remark42__comment-4e913b7e-bbd2-4b7b-9d79-7f81fd217a5e
<details>
<summary>Screenshot</summary>
</details>
2. If you reply to any comment collapser crosses comment form. 
<details>
<summary>Bug</summary>
</details>
<details>
<summary>Fix</summary>
</details>
> Fix free space under comments if is opened by link

- backend/app/rest/api/rest.go
This change increase the speed of updates delivery to one hour, targeting #556.
If we don't have a unique path for static resources per version of remark, we want Cache-Control max-age to be set as low as reasonably possible.
> Lower Cache-Control max-age from 24h to 1h 

- README.md
In Readme:
- fix typo in `image-proxy.cache-external` option
- add `IMAGE_PROXY_HTTP2HTTPS` env variable
- add description to deprecation options section
> Actualise CLI options information in the readme

- README.md
- backend/app/cmd/server.go
- backend/app/notify/email.go
- backend/app/notify/email_test.go
Address #560, the backend part.
When `NOTIFY_EMAIL_SUBSCRIBE_URL` environment variable is provided, instead of embedding token to email it will be included as a link.
With `SITE=http://127.0.0.1` and `NOTIFY_EMAIL_SUBSCRIBE_URL=/subscribe?token=`, link will look like `http://127.0.0.1/subscribe?token=<subscription_token>`. The token is not escaped and I'll escape it if it will be necessary when the frontend part will be written.
After the frontend counterpart will be created, `NOTIFY_EMAIL_SUBSCRIBE_URL` default should be set to newly created URL location.
That's how verification email looks like when subscribe_url is supplied:
> Add subscription link support to notification email verification template

- backend/app/notify/email.go
#577 
<details>
<summary>Bug</summary>
</details>
<details>
<summary>Fix</summary>
</details>
<details>
<summary>Blockquote</summary>
Styling for blockquote was added but it will not be styled for a reply because it is already on a white background
</details>
> fix name line break and add styles for blockquote

- backend/app/rest/api/migrator_test.go
- backend/app/store/image/fs_store_test.go
- backend/app/store/image/image.go
> switch image interpolation to CatmullRom

- backend/app/rest/proxy/image.go
- backend/app/rest/proxy/image_test.go
- backend/app/store/image/bolt_store.go
- backend/app/store/image/bolt_store_test.go
- backend/app/store/image/fs_store.go
- backend/app/store/image/fs_store_test.go
- backend/app/store/image/image.go
- backend/app/store/image/image_mock.go
- backend/app/store/image/image_test.go
- backend/app/store/service/service.go
- backend/app/store/service/service_test.go
1. I have investigated the ability to add remote image store #572 and found the `image.Store` interface a little bit confusing. I have tried to make the intent as clear as possible and demoted internally used commit and cleanup to private methods.
1. replaced immediate commit (in rest/proxy) to delayed one via `Submit`.
1. fixed potential race inside `Close`
1. added some comment
1. minor refactoring
@smaant - pls take a look. Hopefully, it makes sense to you.
> Simpler image service

- .github/workflows/ci-test-frontend.yml
- Dockerfile
- frontend/.eslintignore
- frontend/.size-limit.js
- frontend/app/common/constants.config.ts
- frontend/app/common/constants.ts
- frontend/app/embed.ts
- frontend/package-lock.json
- frontend/package.json
- frontend/webpack.config.js
Motivation:
embed.js file is remark42 loader and it should be smaller as possible.
In this request I removed unused pollyfills and fix IE11 issue with remove dom node. I checked, emed.js works even in IE11.
Size was changed from `25k` to `2.5к`
> Cleanup embed.ts and add limit-size checker

- frontend/.babelrc.js
- frontend/.size-limit.js
- frontend/app/common/constants.config.ts
- frontend/app/common/constants.ts
- frontend/app/common/polyfills.ts
- frontend/app/components/root/in-view/in-view.tsx
- frontend/app/counter.ts
- frontend/app/last-comments.tsx
- frontend/app/remark.tsx
- frontend/app/utils/cmpRef.ts
- frontend/package-lock.json
- frontend/package.json
- frontend/webpack.config.js
- remove core-js for modern browser
- replace core-js promise pollyfill on es6-promise
- make interaction observer polyfill dynamically loaded
- use XMLHttpRequest instead of usage bloat api.ts
- remove `preact/debug` from production build
- replace lodash on lodash-es
as result:
remark.js - 92 KB to 68 KB
last-comments.js - 77 KB to 55 KB
deleteme.js - 32 KB to 18 KB
counter.js - 32.5 KB to 1.05 KB
> Optimize bundle size

- frontend/.size-limit.js
- frontend/app/common/api.getLastComments.ts
- frontend/app/common/api.ts
- frontend/app/common/constants.ts
- frontend/app/components/list-comments/list-comments.tsx
- frontend/app/last-comments.tsx
Not significant reduce but good enought:
`public/last-comments.js` 44.67 KB -> 42.43 KB
* use one api method insted full api file
* remove debug for preact
* use smaller constans file
* move unique constants
> Reduced size of last-comments widget

- frontend/package-lock.json
- frontend/package.json
* update vulnerable packages
* set fresh version of node because of using `Object.fromEntries` in scripts
* add license field
We still have one package which depends on vulnerable dep and it can be updated after merging of this PR https://github.com/dollarshaveclub/es-check/pull/114
> Update js deps

- .golangci.yml
Fix #615. Please remove repo from https://golangci.com/ to prevent errors from happening in the period before service will be decommissioned.
> Remove .golangci.yml file for golangci-lint service

- backend/_example/memory_store/go.mod
- backend/_example/memory_store/go.sum
- backend/app/cmd/server.go
- backend/app/rest/api/rest.go
- backend/app/rest/api/rest_private.go
- backend/app/rest/api/rest_private_test.go
- backend/app/rest/api/rest_test.go
- backend/app/rest/proxy/image_test.go
- backend/app/store/admin/remote_test.go
- backend/app/store/image/bolt_store.go
- backend/app/store/image/bolt_store_test.go
- backend/app/store/image/fs_store.go
- backend/app/store/image/fs_store_test.go
- backend/app/store/image/image.go
- backend/app/store/image/image_mock.go
- backend/app/store/image/image_test.go
- backend/app/store/service/service_test.go
Pre-requirement to #625.
- `SizeLimit` function removed altogether. `MaxSize`, `MaxHeight`, `MaxWidth` properties of the `Store` implementations moved to `ServiceParams`.
- `image.Store.Save` signature included filename. The filename is unused in the current implementation and I got rid of it.
- add clarification commentary to `image.Store` interface
- Image validation and resizing is now done in `Service` and not `Store`
- hide `image.Store` instance is from `image.Service` consumers
- I bumped a couple of modules in `go.mod` to the latest versions.
Disclaimer: remark/backend `v1.5.0` wouldn't work without `replace` directive in `go.mod`, because of #627. But leaving `v1.4.0` in place feels wrong and I bumped it nevertheless.
> image.Service and image.Store improvements

- README.md
- backend/app/cmd/server.go
- backend/app/notify/email.go
- backend/app/notify/email_test.go
- backend/app/notify/notify.go
- backend/app/notify/telegram.go
- backend/app/rest/api/rest.go
- backend/app/rest/api/rest_private.go
- backend/app/rest/api/rest_private_test.go
- backend/app/rest/api/rest_test.go
- compose-dev-backend.yml
- docs/email.md
Add admin email notifications on new comments. Resolves #633.
<details>
<summary>Screenshots</summary>
Emails on new top-level comment and reply to it, with emails to admin and to parent comment user:
Admin notification on top-level comment, style can be improved by frontenders (@akellbl4 ?):
Notification on reply comment (I've removed "for dev_user" from here as well, screenshot is incorrect only about it):
User notification on reply should be unaltered to the current state:
</details>
> Site-wide email notifications for site owner 

- frontend/app/common/api.test.ts
- frontend/app/common/api.ts
Resolves #642
I made a fast fix of it on the frontend by encoding the address.
But I think it would be better to put a payload in the request body because we use POST method and it is a usual way to pass data to backend.
> Encode email in subscribe request

- docs/email.md
As suggested in #655, I've added documentation for email providers:
- Mailgun usage via API
- SendGrid usage via API and SMTP
I've tested all configurations before writing about them.
> Add documentation for using SendGrid and for Mailgun API

- docker-init.sh
Before:
```
➜  docker run umputun/remark42:dev
init container
set timezone America/Chicago (Sat Apr 11 11:19:28 CDT 2020)
custom APP_UID not defined, using default uid=1001
execute /srv/init.sh
prepare environment
/srv/init.sh failed
```
After:
```
➜ docker run umputun/remark42:dev
init container
set timezone America/Chicago (Sat Apr 11 15:30:59 CDT 2020)
custom APP_UID not defined, using default uid=1001
execute /srv/init.sh
prepare environment
ERROR: /srv/var doesn't exist, which means that state of the application
ERROR: will be lost on container stop or restart.
ERROR: Please mount local directory to /srv/var in order for it to work.
/srv/init.sh failed
```
> Fix docker run error without attached /srv/var

- Dockerfile.artifacts
https://github.com/umputun/remark42/issues/444
> fix artifact filename on arm32

- README.md
- backend/app/cmd/server.go
- backend/app/store/image/image.go
- backend/app/store/image/image_test.go
- fix a few things in Readme
- shutdown all services before stopping the application (previously shutting down services was a non-blocking operation and likely did not complete properly)
- fix `image.Service.Close()` as previously it was stuck for eternity in case `image.Service.Submit` was not called at least once during the application run
This PR likely will improve the situation with the problem described in #584 as previously `image.Service.Close()` likely was not even called on program shutdown.
> Application shutdown problem fix

- frontend/app/locales/zh.json
locale: zh.json: fixup typo for subscribeByEmail.submit
> locale: zh.json: fixup typo for subscribeByEmail.submit

- backend/app/notify/email.go
I found this problem when I was refactoring the `email provider` code ( the PR which got rejected by umputun).
a simple test run under my local machine ( 6 core 12 thread CPU with 4.7GHz freq) failed, the test code looks like:
```go
htmlContent := "<strong>simple HTML body goes here</strong>"
t.Logf("try send via SMTP from %s to %s", fromEmail, toEmail)
msg, err := buildMessage(toEmail, htmlContent, "text/html")
if err != nil {
t.Error(err)
}
// now only got the headers, body is missing
t.Logf("mail msg: %s", msg)
if !strings.Contains(msg, htmlContent) {
t.Errorf("BuildMessage lost body")
}
```
look into `quotedprintable.Close()` function, you' find it implicitly called `flush()`:
```go
// Close closes the Writer, flushing any unwritten data to the underlying
// io.Writer, but does not …
```
> smtp buildMessage(): flush quotedprintable writer buff explicitly

- backend/app/notify/email.go
1. second param is wrong
2. most time it does not effact the result, but when you are connecting to a localhost smtp server with 
PLAIN AUTH enabled but without TLS enabled. it will fail
I also marked this problem in my smtp-brd [FAQ](https://github.com/ttys3/smtp-brd#faq)
>  `smtp.plainAuth failed: unencrypted connection`
You need either to setup TLS on your SMTP server,
use localhost as a relay or disable authentication.
the answer come from  
[this issue](https://github.com/prometheus/alertmanager/issues/1358#issuecomment-386209698)
The error is because the Go SMTP package doesn't allow authentication without encryption.
From <https://godoc.org/net/smtp#PlainAuth>
>   PlainAuth will only send the credentials if the connection is using TLS
or is connected to `localhost`. Otherwise …
> notify/email.go: fixup smtp.NewClient second param

- backend/_example/memory_store/server/rpc_test.go
This resolves panic in memory_store tests.
> remove t.Log from test server.Run in memory_store

- .github/workflows/ci-test-backend.yml
I want to resolve #641 and it seems like all problems which we saw related to golangci-lint v1.24.0.
This PR updates lint to the latest minor version before the problem one as well as bumps CI go to 1.14.
> Bump CI go version to v1.14, golangci-lint to v1.23.8.

- README.md
- backend/app/rest/proxy/image.go
- backend/app/rest/proxy/image_test.go
Resolves #614.
- serve `/api/v1/img` requests disregarding if saving of image proxy is enabled or not
This does increase the load time for every proxified image with caching disabled, as we first try to read it from cache anyway.
- document behavior above in the readme
- fix reference to outdated  ENV configuration variable in Readme
>  serve proxified images disregarding if saving is enabled

- Dockerfile.artifacts
I removed this part in docker build in this [PR](https://github.com/umputun/remark42/pull/663/files)
Because it was changed to webpack replacement.
> Remove unused sed from artifacts build

- backend/app/rest/proxy/image.go
- backend/app/rest/proxy/image_test.go
- backend/app/store/image/image.go
- backend/app/store/image/image_test.go
- Close response.Body in image_proxy tests, part of fixing for #591;
- move cachedImgID and sha1Str from rest.proxy to store.image: it's logical to have them there and also they will be needed for me to fix #694.
> Close response.Body in image_proxy tests

- backend/app/cmd/server.go
- backend/app/rest/proxy/image.go
- backend/app/rest/proxy/image_test.go
- backend/app/store/image/image.go
- backend/app/store/image/image_test.go
- backend/app/store/service/service_test.go
Resolves #694.
Behavior before this PR
- Set `EDIT_TIME=20s` and `IMAGE_PROXY_CACHE_EXTERNAL=true` in docker-compose.yml
- Start dev instance using docker-compose, post comment with text `![](https://homepages.cae.wisc.edu/~ece533/images/cat.png)`
- Restart docker-compose
- Wait for 2 minutes
- Reload the page: image from the comment will be re-loaded as it was stuck in Staging without commit and then was deleted after `EDIT_TIME*5`, `1m40s` in this case. And with current logic, we re-load it in case it's not in storage.
Behavior after this PR
- Set `EDIT_TIME=20s` and `IMAGE_PROXY_CACHE_EXTERNAL=true` in docker-compose.yml
- Start dev instance using docker-compose, post comment with text `![](https://homepages.cae.wisc.edu/~ece533/images/cat.png)`
- Restart docker-compose
- Wait for 2 …
> Commit proxy images same (delayed) way as normally uploaded ones

- backend/app/cmd/server.go
- backend/app/rest/api/rest_public_test.go
[go-consistent](https://github.com/quasilyte/go-consistent)-proposed changes.
I couldn't satisfy one of them (`./app/cmd/server_test.go:492:13: arg list parens: align `)` to a same line with last argument`) but all others are covered in this PR. I wonder if that makes any sense, maybe not fully but partially?
> go-consistent proposed changes

- backend/app/cmd/server.go
- backend/app/store/service/service.go
- backend/go.mod
- backend/go.sum
- backend/vendor/modules.txt
This gets rid of the direct dependency on go-cache. Leaking goroutines from it because of [go-pkgz/jrpc](https://github.com/go-pkgz/jrpc) imports [didip/tollbooth](https://github.com/didip/tollbooth/blob/master/limiter/limiter.go) which use go-cache.
I'll prepare PR to didip/tollbooth as well to get closer to eliminating go-cache leaking goroutines: for a start, I've created an issue https://github.com/didip/tollbooth/issues/84.
> Switch from go-cache to lcw

- backend/app/cmd/avatar.go
- backend/app/cmd/server.go
- backend/app/cmd/server_test.go
The testing a new scenario I found that we are leaking goroutines after error after datastore is created, and also we lack of context in a particular set of errors.
> Add context to server errors, properly close datastore in case of errors

- README.md
- backend/app/cmd/server.go
- backend/app/cmd/server_test.go
Use new `eventbus.NewRedisPubSub` to enable distributed cache support in remark42.
Tests are written only for the failure of new cache creation. Testing its work would require setting up a redis and doing black-box cache testing which might be complex but I could do it if it's necessary.
> add distributed cache support via redis

- README.md
- backend/app/migrator/disqus.go
- backend/app/migrator/disqus_test.go
- backend/app/migrator/native.go
- backend/app/migrator/native_test.go
- backend/app/migrator/wordpress.go
- backend/app/migrator/wordpress_test.go
- backend/app/store/comment.go
- backend/app/store/image/image.go
- backend/app/store/image/image_test.go
- backend/app/store/service/service.go
- backend/app/store/service/service_test.go
I tried to import batch of comments via native importer. I notices that importing frozen at 5000 comment, due to size of buffered channel in image service. It was continued after ttl (1.5  edit time) had expired, and stuck again.
So, this PR contains possible solution -- using not current time to check comment edit time expiration before indexing images, but actual comment timestamp.
I am not sure that it is the best solution and maybe some other needs to be considered. For example non-blocking version of submit, of forcing submition for importer.
> Fix stuck in image submit while importing comments from backup

- frontend/package-lock.json
- frontend/package.json
- frontend/webpack.config.js
* automatic update vulnerable dependencies with `npm audit`
* update copy-webpack-plugin to next major version
* update webpack config connected with new copy-webpack-plugin API
We still have vulnerable modules but all of them in development dependencies.
> Update vurnulable deps

- README.md
- backend/app/cmd/server.go
- backend/app/rest/api/rest.go
- backend/app/rest/api/rest_private.go
- backend/app/rest/api/rest_test.go
This is a fix for #756, after this change user would be able to set multiple admin emails and all of them will be used for admin notifications.
That's a simple approach to this problem, a more sophisticated one would be introducing admins per-site, who will receive notifications for their sites. It might be useful for single remark42 instance with multiple different sites, but on the other hand, I think that we might discourage that pattern and force users to run multiple instances of remark42 in separate docker containers if they want to host completely different sites together.
> add ability to set multiple admin emails for notifications

- Dockerfile
- Dockerfile.artifacts
- backend/.golangci.yml
- backend/app/notify/email.go
- backend/app/templates/templates.go
- fix `go test -race` build problem discovered in #788
- set minimum version of TLS for the backend email client to 1.2 (gosec requirement)
- remove unnecessary filepath.Join from the backend templates (gocritic mentioned that it doesn't make sense)
- increase golangci-lint timeout from default 1m to 5m
> Fix Dockerfile build

- docs/1.6/email.md
- docs/latest/email.md
Images in docs on the site were with broken paths.
> Fix images paths in docs

- backend/app/notify/email.go
- backend/app/notify/email_test.go
- backend/app/notify/notify.go
- backend/app/notify/notify_mock.go
- backend/app/notify/notify_test.go
- backend/app/notify/telegram.go
- backend/app/notify/telegram_test.go
- backend/app/rest/api/rest_private.go
- backend/app/rest/api/rest_private_test.go
This is the first step towards recursive email notifications implementation in #758. I figured out that the current `notify.Request` contains two different use cases and API would be much more clear if they would be separated into their own methods.
This PR creates `notify.SubmitVerification` and `notify.Destination.SendVerification` which moves verification metadata away from `notify.Request`.
> Separate notify.SubmitVerification from notify.Submit

- backend/app/notify/email.go
- backend/app/notify/email_test.go
- backend/app/notify/notify.go
- backend/app/notify/notify_test.go
- backend/app/notify/telegram.go
- backend/app/rest/api/rest_private.go
- backend/app/rest/api/rest_private_test.go
This PR moves more email notification logic from `notify.Submit` callers and `notify.Submit` itself into `Email.Send`. In particular, it starts handling user and admin email notifications in a single `Email.Send` to hide this logic from `notify.Submit`. As a tradeoff, I had to move email user verification logic to `notify.getNotificationEmails`, as I'll need it there for recursive notifications.
The new logic flow is extensively tested with existing tests as well as the newly created one.
Also, this PR hides user email from error and logs messages about canceled context and adds a test for covering default template settings.
> Clarify notify.Email implementation and notify logic

- backend/app/notify/notify.go
- backend/app/notify/notify_test.go
Send email notifications recursively up the chain of comments. Changes the default behavior.
Relies on merging #796 first. Will resolve #758.
> Recursive email notifications

- docker-init.sh
- frontend/comments.ejs
- frontend/counter.ejs
- frontend/index.ejs
- frontend/last-comments.ejs
- frontend/webpack.config.js
I installed remark42 in the easiest way from the docker. Configured nginx to use app without subdomain. It works okay for comments but widgets not working as expected. Widgets use it own config with host as window.location.origin which returns the fqdn only.
This can be fixed on server side by multiple sed commands in container like this `docker exec -it remark42 sed -i "s|host: window.location.origin|host: 'https://b.sattellite.me/comments/'|g" /srv/web/last-comments.html`
I prepared fix to code for exclude this problem in future:
- Replaced host value from window.location.origin to "REMARK_URL" || window.location.origin.
- Changed init script for container to replace forced `site_id` by 'remark' to environment SITE_ID.
> Fixed build for usage without subdomain

- frontend/app/common/constants.ts
- frontend/app/components/auth/__email-login-form/auth__email-login-form.test.tsx
- frontend/app/components/auth/__email-login-form/auth__email-login-form.tsx
- frontend/app/components/comment-form/__subscribe-by-email/comment-form__subscribe-by-email.test.tsx
- frontend/app/components/comment-form/__subscribe-by-email/comment-form__subscribe-by-email.tsx
- frontend/app/components/root/root.tsx
Before, if user was logged in by email and wanted to subscribe, he had to enter his email again.
Now, if user is logged in by email and presses email subscription button, user's email is already filled in the form.
> Save logged in user email in local storage

- docs/1.6/migration.md
- docs/latest/developers-guide/email-templates.md
- docs/latest/migration.md
- Fix formatting for email templating doc, published [in docs](https://remark42.com/docs/latest/developers-guide/email-templates/) section
- Add remap doc kindly contributed by @mind-overflow, resolves #810
> documentation: fix email templating doc, add remap doc

- README.md
- backend/app/cmd/server.go
- backend/app/rest/api/rest.go
- backend/app/rest/api/rest_test.go
This PR adds `--allowed-hosts` (env:"ALLOWED_HOSTS") enforcing  frame-ancestors Content-Security-Policy to limit which sites can include remark42 in any kind of frame. Related to https://github.com/umputun/remark42/issues/836
For more details about frame-ancestors see https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy/frame-ancestors
> add optional frame-ancestors (Content-Security-Policy) for the list of hosts passed by user

- backend/app/store/formatter.go
- backend/app/store/formatter_test.go
This seems to be a good optimization because in many cases comments are outside of the active view
> enforce loading=lazy attribute to rendered images html

- backend/app/rest/api/rest_private_test.go
- backend/app/store/comment.go
- backend/app/store/comment_test.go
- backend/app/store/service/service.go
- backend/app/store/service/service_test.go
`voted_ip` map was added to comments as a part of #400, however I don't think there is a reason to send it back to UI/API clients. We already strip `votes` map of user on both send and input validation levels and I believe the same should be done for `voted_ip` as well.
Looks like this data not in any use by the official clients, so this PR strips it completely. Pls note - presence of this map in the response doesn't expose anything bad by itself (just a bunch of hashes and time stamps) but may allow some cross-post analysis of votes to figure how the same user voted without exposing the user ID. So, not terrible but still something we may want to prevent.
> strip voted_ip from response

- .github/workflows/ci-frontend-size-limit.yml
- .github/workflows/ci-frontend.yml
- Fix `size-limit` action
- `size-limit` has its own file because has a different trigger
- Rename `ci-test-frontend` -> `ci-frontend` because it's doing more than just tests
- Separate typescript type check and translations for more atomic and informative error in case of fail
- All frontend actions grouped under `frontend` label
- Update node to lastest LTS
> Update frontend CI

- README.md
I put back the old code snippet because the new one could work only with master version.
By the way, the old snippet will work with the new remark version just fine.
> Rollback readme till release

- backend/app/migrator/disqus.go
- backend/app/migrator/disqus_test.go
- backend/app/store/user.go
I found a bug while importing comments from Disqus.
It generates `comment.User.ID` from author's username. 
https://github.com/umputun/remark42/blob/3628467367277be356fd56d4590ca1740a121cd7/backend/app/migrator/disqus.go#L130-L134
If author's username is empty (`c.User.ID == "disqus_"`), it uses author's name for user ID. It assumes `store.EncodeID` returns empty string for empty username.
https://github.com/umputun/remark42/blob/3628467367277be356fd56d4590ca1740a121cd7/backend/app/migrator/disqus.go#L140-L142
But `store.EncodeID` returns `da39a3ee5e6b4b0d3255bfef95601890afd80709` for empty string.
https://github.com/umputun/remark42/blob/3628467367277be356fd56d4590ca1740a121cd7/backend/app/store/user.go#L52-L54
`reValidSha.MatchString(val)` doesn't return `true` for empty values. …
> Fix empty username check for Disqus migrator

- backend/app/notify/email.go
- backend/app/notify/email_test.go
Add base64-encoding to email `Subject:` header value to allow non-ASCII characters, according to RFC2047. Current implementation produces invalid messages when e.g. page title contains Cyrillic letters.
> Encode e-mail subject to support non-ASCII chars

- frontend/app/embed.ts
This patch fixes NPE from #722, tested in Firefox 85 an Edge 88 (Chromium).
The idea is to manually set `titleObserver = null` in `destroy()` and allow browser's GC to drop the observer, it's callback and captured iframe. Function `postTitleToIframe` is not called after destroy call, but I've also added null checks for functions which send messages to iframe window.
> Fix NPE when sending message to detached frame

- frontend/app/embed.ts
- frontend/templates/iframe.ejs
**Problem**
When clicking on a username and show a user's info main iframe with comments collapses.
**Bug**
Somehow after add `padding: 6px` on `body` it lost height.
**Solve**
Just add 100% of height on HTML and body.
Do not add `margin` to iframe with user info.
> Fix collapsing comments iframe

- frontend/templates/iframe.ejs
User info widget is able to change iframe height of comments widget. It's really terrible.
In the new auth, I added padding to the page, and it excited the limit of 10px that was hardcoded for the iframe's height change. It cased iframe resize to 22px. Now I just increased that number of pixels.
> Resize only comments iframe, prevent to resize iframe by comments info

- README.md
When importing a file with comments in Disqus format, the correct path of that file for is `/srv/var/{disqus-export-name}.xml`. This should be made clear in the command template.
Signed-off-by: Michael Picht <mipi@fsfe.org>
> corrected path in docker command to import comments from disqus

- frontend/app/common/local-storage.ts
- frontend/app/components/comment-form/comment-form.tsx
**The problem**
When local storage is empty and we try to upload an image and send a form shows an error but the comment saves.
**Why**
Comment saves to local storage on edit.
When a user uploads an image comment doesn't save in local storage.
On send, we are trying to remove a saved comment from local storage but it's empty.
`delete data[....]` when data is `null`
**Solve**
* save comment after image upload
* do not affect error messages by saving to LS mechanism
* don't try to clear empty local storage
> Fix saving comment to LS

- backend/app/notify/notify_mock.go
- backend/app/notify/notify_test.go
Started flapping in Go 1.16 for unknown reasons, something became quicker or slower and timings became off. This gives more time for test to pass.
> fix flapping notify drops test, clarify debug logs

- backend/app/notify/notify_test.go
Instead of waiting for exactly one message to drop, now it checks for at least one message to drop.
> make flapping notify drops test less sensitive

- README.md
The link to Frontend guide in main readme was in camel case like Readme.md, 
404 page shows.
> fix link to Frontend guide in README

- frontend/app/utils/parseQuery.ts
Changes parseQuery implementation to URLSearchParams. 
I'm using .forEach() because not all browsers support URLSearchParams.entries()
> #898 Replace parseQuery with URLSearchParams

- frontend/app/components/auth/components/oauth.spec.tsx
- frontend/app/components/auth/components/oauth.tsx
Fixes the OAuth links when remark works on the same domain as the site.
> use remark_config.host for oauth links

- README.md
- backend/app/main.go
The best way to benefit everyone from the answer in discussions is to add it in places the information is relevant.
> clarify --secret usage based on #861

- frontend/templates/comments.ejs
- frontend/templates/counter.ejs
- frontend/templates/demo.ejs
- frontend/templates/iframe.ejs
- frontend/templates/last-comments.ejs
Now we have two requests for the js bundle because we don't add `type="module"` when requesting it.
This PR is fixing it.
> add type module while load modern js bundle

- frontend/app/components/auth/auth.tsx
- frontend/app/components/auth/components/button.tsx
- frontend/app/components/auth/components/oauth.tsx
- frontend/app/components/comment-form/text-expander.tsx
- frontend/app/components/input/index.ts
- frontend/app/components/input/input.tsx
- frontend/app/components/list-comments/list-comments.tsx
- frontend/app/components/root/root.tsx
- frontend/package-lock.json
- frontend/package.json
A simple replace [classnames](https://github.com/JedWatson/classnames) to [clsx](https://github.com/lukeed/clsx)
clsx is smaller and faster version of classnames.
Also, `classnames/bind` was rid of from the project.
> replace module `classnames` to faster and smaller `clsx`

- frontend/package-lock.json
- frontend/package.json
- frontend/webpack.config.js
I've got the idea [here](https://www.freecodecamp.org/news/reducing-css-bundle-size-70-by-cutting-the-class-names-and-using-scope-isolation-625440de600b/) and reimplemented it in our project in favor of reducing JS and CSS bundle size as well.
UPD. When we fully migrate on CSS Modules size of JS and CSS should drop due to using this shorting mechanism.
> make classnames short

- README.md
- backend/app/cmd/server.go
- backend/app/rest/api/rest.go
- backend/app/rest/api/rest_private.go
- backend/app/rest/api/rest_public_test.go
- backend/app/store/service/service.go
- backend/app/store/service/service_test.go
Adds backend support for #946. New param `--admin-edit` (env: ADMIN_EDIT) disables both edit window and "has replies" check for admin's comments.
> Admin edit

- README.md
- backend/app/cmd/server.go
- backend/app/rest/api/rest.go
- backend/app/rest/api/rest_test.go
- backend/app/rest/api/ssl.go
adding new option "address" allowing binding to a particular interface/address 
re: #1000
> add ability to select listening address #1000

- backend/.golangci.yml
- backend/app/rest/api/admin_test.go
- backend/app/rest/api/migrator_test.go
- backend/app/rest/api/rest_private_test.go
- backend/app/rest/api/rest_public_test.go
- backend/app/rest/api/rest_test.go
- backend/app/rest/proxy/image.go
Found few places which were not properly closed, so enabled the linter to detect these.
> Close the HTTP client body in tests, add lint

- frontend/app/common/types.ts
- frontend/app/common/user-info-settings.ts
- frontend/app/components/auth-panel/auth-panel.tsx
- frontend/app/components/dropdown/dropdown.tsx
- frontend/app/components/root/root.tsx
- frontend/app/embed.ts
- frontend/app/utils/postMessage.ts
- frontend/templates/iframe.ejs
Resolve https://github.com/umputun/remark42/issues/897
I searched through the files in the frontend, in all places where I found postMessage removed unnecessary serialization.
Also, I think if we haven't stringify, then we don't need to check for string type here.
https://github.com/umputun/remark42/blob/553bcf2fd59e400fa2f0ee4ddfa70eb9044f9f2f/frontend/app/components/root/root.tsx#L187
> PostMessage without serialization

- backend/app/rest/api/rest_private.go
- backend/app/rest/api/rest_private_test.go
- backend/app/rest/api/rest_public.go
- backend/app/rest/api/rest_public_test.go
- backend/app/rest/api/rest_test.go
- backend/app/rest/httperrors.go
- backend/app/store/image/image.go
That should cover the case when an image is posted after it cleaned up or the URL is altered by mistake: in case image belongs to this site, it should be working at the time of preview or comment post.
> Validate image existence before post or preview

- frontend/app/utils/errorUtils.ts
- Resolve #1005
- Fix error message about the read-only mode
> Add a new error message and correct another one

- backend/app/rest/api/rest_private.go
- backend/app/rest/api/rest_public.go
- backend/app/store/image/image.go
- backend/app/store/image/image_test.go
- backend/app/store/service/service.go
That function returns an error in a never expected condition, and that error would be logged message on the caller side: none of the callers handles it.
That change hides that error from the caller so that function would have a signature that better fit what it does and how it behaves.
> Remove error return from ExtractPictures

- frontend/app/components/auth/auth.module.css
- frontend/app/components/auth/components/oauth.module.css
- change title color
- change labels color when  2 OAuth providers are used
<details>
<summary>Before</summary>
</details>
<details>
<summary>After</summary>
</details>
> fix oauth view text color

- Dockerfile
That would prevent the [entrypoint script](https://github.com/umputun/baseimage/blob/master/base.alpine/files/init.sh) failure on init.sh while running as "app" and not "root".
Resolves error reported in #1007.
> copy init script earlier than we change /srv owner

- frontend/app/components/root/root.tsx
> fix mobile navigation to comment for hidden comments

- README.md
- backend/app/cmd/server.go
- compose-dev-backend.yml
- docs/latest/telegram.md
This simplifies token and timeout reuse for `notify` module (used now) and for `auth` module later (not yet in the code). SMTP credentials are already set up that way.
Part of the work on #707.
> Move telegram token and timeout to a separate CLI section

- backend/app/cmd/server.go
- backend/app/cmd/server_test.go
Add all auth providers to tests for consistency, reset all variables containing sensitive data on remark42 start (a couple were missing). Changes were done in #1022, but I thought it makes sense to merge them separately.
> Cover all auth providers with tests, clean up env

- docker-init.sh
That change ensures that in a situation like described in #1007, chown doesn't fail silently but carries on with a warning log message, and shows precisely what is wrong in the log. Log after the change:
```
remark42-dev  | changing ownership of /srv/var to app:app (remark42 user inside the container)
remark42-dev  | chown: /srv/var/docker-init.sh: Read-only file system
remark42-dev  | WARNING: /srv/var ownership change failed, if application will fail that might be the reason
remark42-dev  | execute "/srv/remark42 server"
remark42-dev  | remark42 verbose_chmod-adbd73a-20210524T05:22:15
```
> Make docker init script chown command verbose

- backend/_example/memory_store/accessor/image.go
- backend/_example/memory_store/server/image.go
- backend/_example/memory_store/server/image_test.go
- backend/_example/memory_store/server/rpc.go
- backend/app/rest/api/rest_public.go
- backend/app/rest/api/rest_public_test.go
- backend/app/store/image/bolt_store.go
- backend/app/store/image/bolt_store_test.go
- backend/app/store/image/fs_store.go
- backend/app/store/image/fs_store_test.go
- backend/app/store/image/image.go
- backend/app/store/image/image_mock.go
- backend/app/store/image/image_test.go
- backend/app/store/image/remote_store.go
- backend/app/store/image/remote_store_test.go
- backend/app/store/service/service_test.go
That PR will delay the image clean up after it's loaded by preview, so the commenter would have more time to post it before cleanup removes it.
Also, reset the cleanup time on images in the submitted comment to prevent the situation when they are deleted from temporary storage before being move to the permanent one, waiting for comment EditDuration to expire. That resolves #909.
> Renew image time to cleanup on comment Preview and Submit

- backend/app/notify/telegram.go
Prior to this PR we are ignoring provided timeout value.
> Start using the provided timeout in the telegram notify

- backend/app/cmd/cmd.go
- backend/app/cmd/server.go
- backend/app/cmd/server_test.go
- backend/app/main.go
It turned out we don't really want to break users configurations, so deprecated values stay with us at least before 2.0 is released.
> Clarify deprecation messages

- backend/app/cmd/server.go
- backend/app/cmd/server_test.go
Before:
```
failed to make notify service, failed to create email notification destination:
can't set templates:
can't read message template:
open email_reply.html.tmpl:
no such file or directory
```
After:
```
make notify, types=[email]
create notifier service, queue size=100, destinations=1
```
> Fix email templates path in tests

- README.md
- backend/app/cmd/server.go
- backend/app/cmd/server_test.go
- compose-dev-backend.yml
- docs/latest/email.md
- docs/latest/slack.md
- docs/latest/telegram.md
The current state is a mess of user and admin notifications, which will become worse after implementing the new user notification methods like a telegram.
This change makes things simpler for the remark42 users.
Can be merged after #1026 will be merged.
> Separate user and admin notifications

- frontend/app/common/user-info-settings.ts
- frontend/app/components/auth-panel/auth-panel.tsx
- frontend/app/components/auth/auth.hooks.ts
- frontend/app/components/comment/comment.tsx
- frontend/app/components/dropdown/dropdown.tsx
- frontend/app/components/root/root.tsx
- frontend/app/components/user-info/user-info.tsx
- frontend/app/embed.ts
- frontend/app/remark.tsx
- frontend/app/store/user-info/actions.ts
- frontend/app/utils/parseQuery.ts
- frontend/app/utils/postMessage.ts
- frontend/templates/iframe.ejs
- fix user info opening
- remove iframe height checks by interval
- update height by mutation observer events
- rename events
> post messages from iframe

- backend/app/cmd/server.go
- backend/app/main.go
- backend/app/notify/telegram.go
- backend/app/notify/telegram_test.go
As discussed off-GitHub, remove the ability to set Telegram API (as it's used only in tests) and notify parameters passed as structure in the same way we do with Email notifications now.
> Remove ability to set telegram API, clarify telegram notify params

- backend/_example/memory_store/accessor/data.go
- backend/_example/memory_store/accessor/data_test.go
- backend/_example/memory_store/accessor/image_test.go
- backend/app/notify/notify.go
- backend/app/notify/notify_test.go
- backend/app/rest/api/admin.go
- backend/app/store/engine/bolt.go
- backend/app/store/engine/bolt_test.go
- backend/app/store/engine/engine.go
- backend/app/store/service/service.go
- backend/app/store/service/service_test.go
For telegram notifications we'll need to get a telegram user ID from the user and store and retrieve it later, this PR adds support for that user details and improves a bunch of tests in affected modules.
All newly added code is tested.
> Add UserDetailTelegram support

- README.md
I had trouble understand why I was getting `no such file or directory` errors 🙂
> docs(import): clarify import path for wordpress

- .gitignore
- backend/app/notify/telegram.go
- backend/app/notify/telegram_test.go
- backend/templates/email_confirmation_login.html.tmpl
- backend/templates/email_confirmation_subscription.html.tmpl
A couple of changes to telegram notifications and error handling code, email text improvements, ignore IntelliJ Idea rest requests variables file.
Reply notification text, now more consistent with the email notification, and the same which will be used for user notifications. Before:
After:
Part of #1029 is not strictly tied to the telegram user notifications, and I wanted to merge separately.
> Multiple notify module improvements

- frontend/app/common/fetcher.test.ts
- frontend/app/common/fetcher.ts
An HTTP header cannot be empty, and although some webservers allow this (nginx, Apache), others answer 400 Bad Request (lighttpd), preventing the widget from loading.
I'm not sure this is the most elegant way to do it, that's why this is marked as a draft.
> Don't set X-XSRF-TOKEN when the user isn't logged in

- README.md
- backend/app/cmd/server.go
- backend/app/cmd/server_test.go
- compose-dev-backend.yml
Backend support for telegram auth, #707.
> add telegram auth backend support

- README.md
- SECURITY.md
- backend/_example/memory_store/README.md
Add a bunch of newlines where it is appropriate and stick to formatting with no line breaks as we don't have them in most of the existing documentation, making the markdown files more consistent.
Also, indent embedded yaml files with two spaces for better readability.
> Apply consistent formatting for markdown files

- site/.prettierrc
- site/src/docs/backup/url-migration/index.md
- site/src/docs/configuration/email/index.md
- site/src/docs/configuration/kubernetes/index.md
- site/src/docs/configuration/notifications/index.md
- site/src/docs/configuration/reproxy/index.md
- site/src/docs/configuration/subdomain/index.md
- site/src/docs/getting-started/installation/index.md
- use doublequote in yaml
- right indentation in yaml
- format missformatted places
> format md files

- frontend/app/common/constants.config.ts
- frontend/app/common/constants.ts
- frontend/app/counter.ts
- move once used const to the chunk
- remove unused const
> fix: constants

- README.md
- backend/app/cmd/server.go
- backend/app/cmd/server_test.go
- backend/app/main_test.go
- backend/app/notify/webhook.go
- backend/app/notify/webhook_test.go
This is a PR for the requested feature [#924]
There are not many details in the request, so feel free to specify any requirements. Any feedback is appreciated.
> Webhook  notify

- backend/app/main_test.go
- backend/app/store/service/service_test.go
It flaps (see #380), and with this change, it will have more time to get the expected output in the flaky GitHub Actions environment.
The latest example of false positive: [link](https://github.com/umputun/remark42/pull/1121/checks?check_run_id=3512621950#step:6:49).
> make TestService_UserReplies more robust

- backend/app/cmd/server.go
- backend/app/notify/notify.go
- backend/app/notify/telegram.go
- backend/app/notify/telegram_test.go
- backend/app/providers/telegram.go
- backend/app/providers/telegram_test.go
- backend/app/rest/api/rest.go
- backend/app/rest/api/rest_private.go
- backend/app/rest/api/rest_private_test.go
- backend/remark.rest
Previously it was done through writing bot first, clicking a button, copying the token, and pasting it into the web interface.
The new flow is way simpler: click the link to write bot a message, then click the "Check" button in the web UI and you got notifications enabled.
Unsolved problems:
> Enable telegram notify trough writing bot a message

- site/src/docs/configuration/email/index.md
Email documentation had some troubles with formatting here and there. That PR fixes that.
> Properly format email documentation

- backend/app/cmd/server.go
- site/src/docs/configuration/notifications/index.md
- site/src/docs/configuration/parameters/index.md
Clarification based on [this](https://github.com/umputun/remark42/issues/1189#issuecomment-994672256) discussion.
This PR syncs CLI and documentation parameter descriptions and added clarification to the documentation on how to obtain the ID.
> clarify telegram channel ID param and documentation

- backend/app/cmd/server.go
- backend/app/cmd/server_test.go
Default configuration for notify.type is "none", and prior to this change, it was issuing the deprecation warning which was not intended behavior.
Fixes #1191.
> Do not issue deprecation warning on notify.type by default

- backend/app/notify/telegram.go
- backend/app/notify/telegram_test.go
Real comments:
Notification in Telegram before this PR:
Notification in Telegram after this PR:
> Fix formatting for telegram reply notifications

- backend/app/cmd/server.go
- site/src/docs/configuration/notifications/index.md
- site/src/docs/configuration/parameters/index.md
- site/src/docs/configuration/telegram/index.md
- site/src/docs/nav.json
This PR:
- clarifies CLI params for slack and webhook notifications
- adds documentation for enabling webhook notifications
- adds an explanation of the difference between user and admin notifications
- moves telegram notifications description to separate documentation and improves it
- adds documentation on enabling telegram auth
/cc @BenRoe for review.
> Improve notifications documentation (telegram, webhook)

- site/src/includes/components/docs-aside.njk
Issue: https://github.com/umputun/remark42/issues/1168
Default state of CONTRIBUTING menu group:
> Remove expandability of menu items from docs site

- site/.eleventy.js
- site/src/docs/getting-started/integration-with-gatsby/index.md
- site/src/docs/nav.json
As per request from @paskal [here](https://github.com/umputun/remark42/discussions/1220#discussioncomment-1941628), adding some documentation about integrating Remark42 with Gatsby
> Integrating Remark42 with Gatsby (documentation)

- site/src/docs/configuration/telegram/index.md
Pointed out in #1221 originally. Kudos to @elmaester for pointing it out.
> Add "invite your tg bot" note to documentation

- site/src/docs/configuration/telegram/index.md
Improvements based on testing and trying to set up new notifications based on the documentation.
> Improve telegram notifications documentation

- .gitignore
- site/src/docs/configuration/telegram/index.md
- site/src/docs/contributing/development/backend/index.md
- site/src/docs/contributing/development/frontend/index.md
- site/src/docs/contributing/development/index.md
- site/src/docs/contributing/translations/index.md
Remove generic development documentation, make frontend and backend pages more specific and self-sufficient, as previously you had to read development and frontend pages in order to understand how to properly develop frontend.
> Improve backend and frontend development docs

- backend/app/cmd/cmd.go
- backend/app/cmd/server.go
- backend/app/cmd/server_test.go
- backend/app/main.go
For example, when notify.telegram.token and telegram.token are both set but to different values, user might see "access denied" error in log on attempt to send telegram notification, thinking that notify.telegram.token value is used, when in fact it is ignored and only telegram.token is used.
New behavior is the same, ignoring the old param when new one is set, but issuing the error log message which explicitly tells the user about that.
Resolves #1218.
> Log when deprecated and new args are set at the same time

- site/src/docs/contributing/development/index.md
The text in the backend development section should be backend instead of frontend
> Fix typo in index.md

- backend/_example/memory_store/compose-dev-memstore.yml
- compose-dev-backend.yml
- compose-dev-frontend.yml
- docker-compose.yml
- site/src/docs/manuals/kubernetes/index.md
- site/src/docs/manuals/reproxy/index.md
We have plenty of paths used in the application (like `AVATAR_FS_PATH`, `IMAGE_FS_PATH`), but two of them are hardcoded in examples all over the code for historical reasons.
I found that by default in Docker, the path would anyway resolve to the value we are setting it explicitly to, so it doesn't make sense to set a few variables we are setting now explicitly.
I was confused by these two variables when figuring out how to run the application outside of docker by looking at the default variables we propose in docker-compose.yml.
> Remove explicit /srv/ usage from docker-compose files

- frontend/app/common/fetcher.ts
- frontend/app/common/local-storage.ts
- frontend/app/components/auth/auth.hooks.ts
- frontend/app/components/auth/auth.messsages.ts
- frontend/app/components/auth/auth.module.css
- frontend/app/components/auth/auth.tsx
- frontend/app/utils/is-object.spec.ts
- frontend/app/utils/is-object.ts
- fix type for an error in fetcher
- use is-object func for checks
- better error handling for auth requests
> Fixes for telegram auth

- .github/workflows/ci-frontend.yml
- Dockerfile
- frontend/package-lock.json
- frontend/package.json
- frontend/webpack.config.js
- site/src/docs/contributing/development/frontend/index.md
- upgrade webpack dev server and some webpack loader
- align  nodejs version to 16 in `Docker` and CI steps
> add support node 17

- Dockerfile
- compose-dev-frontend.yml
- site/src/docs/contributing/development/backend/index.md
- site/src/docs/contributing/development/frontend/index.md
That option allows having backend-only build, skipping the long frontend build and test step. Frontend developers run NodeJS locally and usually don't need to have frontend built inside the docker image.
Resolves #1264.
> Allow skipping frontend build in Docker

- site/src/docs/configuration/authorization/index.md
- site/src/docs/manuals/kubernetes/index.md
- add variables mentioned in the auth instructions
- use remark42.mysite.com consistently in documentation
- renew Google auth documentation
> Improve auth documentation

- frontend/.size-limit.js
- frontend/app/components/button/_kind/_link/button_kind_link.css
- frontend/app/components/comment-form/__field/comment-form__field.css
- frontend/app/components/comment/__action/comment__action.css
- frontend/app/components/comment/__control/comment__control.css
- frontend/app/components/comment/__controls/comment__controls.css
- frontend/app/components/comment/comment.css
- frontend/app/components/comment/comment.tsx
- frontend/app/components/list-comments/list-comments.module.css
- frontend/app/components/list-comments/list-comments.tsx
- frontend/app/components/raw-content/raw-content.css
- frontend/app/last-comments.tsx
- frontend/app/styles/global.css
- frontend/templates/last-comments.ejs
- frontend/templates/markdown-help.html
Resolves #1268
- changes base font to system font
- adjustments for comment styles accordingly to the  new font
- adjustments for comment action button styles accordingly to the new font
- use `remark.css` for all of the widgets because it contains all of the necessary fonts and can be cached one time. that means no need to load other chunks and increase the amount of code for download
> use default system font

- frontend/app/styles/custom-properties.css
`color-scheme: dark` makes iframe background lighter than original website.
Bug:
After fix:
> fix light bg on dark theme

- frontend/.size-limit.js
- frontend/app/last-comments.tsx
- frontend/templates/last-comments.ejs
When I removed `last-comments.css` and started to use `remark.css` instead we got base page styles overwritten by those styles. Now I'm moving the file back in order to fix the issue.
> Move back last comments css file

- frontend/app/components/comment/comment-votes.spec.tsx
- frontend/app/components/comment/comment-votes.tsx
- frontend/app/components/comment/comment.tsx
- enable downvoting for only positive. it should give ability to downvote until score is 0
- restore low_score state of a comment. it should make comment semi transparent when downvoted
> fix positive_score and low_score comments options

- backend/app/cmd/avatar_test.go
- backend/app/cmd/backup.go
- backend/app/cmd/cleanup.go
- backend/app/cmd/import.go
- backend/app/cmd/remap.go
- backend/app/cmd/server_test.go
- backend/app/main_test.go
- backend/app/rest/api/admin_test.go
- backend/app/rest/api/migrator_test.go
- backend/app/rest/api/rest_private_test.go
- backend/app/rest/api/rest_public_test.go
- backend/app/rest/api/rest_test.go
- backend/app/rest/api/ssl_test.go
- backend/app/rest/proxy/image.go
- backend/app/store/engine/remote.go
- backend/app/store/service/title.go
- cleanup files in `/tmp` after integrational tests
- call CloseIdleConnections on `http` clients, as without this `go.uber.org/goleak` reports leaking goroutine caused by HTTP client on many tests when ran one by one.
> Improve tests reliability

- backend/app/store/formatter.go
- backend/app/store/formatter_test.go
> Links rune

- backend/app/cmd/server.go
[Direct](https://github.com/go-pkgz/auth/blob/fa21d23/provider/direct.go#L99-L102) auth from go-pkgz/auth [used](https://github.com/umputun/remark42/blob/90e5373/backend/app/cmd/server.go#L834-L861) in Remark42 for anonymous authentication. The problem is that as soon as a user logs in with the same name as another anonymous user, they get precisely the same user ID and can delete or alter messages by that other user.
To prevent that, we need to provide custom [UserIDFunc](https://github.com/go-pkgz/auth/blob/fa21d23ff361c2728f10807ba3dda386ef0c541b/provider/direct.go#L41), which I propose should return hashed IP of the user so that there will be no way another anonymous user and I get the same ID at the same time, but it would be possible to re-login right away with the same ID if I want …
> Protect anonymous comments from being changed by other users

- backend/app/cmd/server_test.go
- backend/app/rest/api/rest.go
- backend/app/rest/api/rest_test.go
PR adds a middleware checking "user" query param similarly to the current UI implementation, with `^[\p{L}\d\s_]{4,64}$` regex.
This is needed to prevent direct API calls from sending non-sanitized data into `/auth/email/login` endpoint. Also, see [related PR](https://github.com/go-pkgz/auth/pull/119) in auth lib
> add email auth validation with middleware

- .dockerignore
- Dockerfile
- Dockerfile.artifacts
- Makefile
- compose-dev-backend.yml
_this related to the discussion in #269_
Remove .git from the docker build context and pass both GITHUB_REF and GITHUB_SHA from the make. It uses an [updated baseimage](https://github.com/umputun/baseimage/commit/40677b819d9b4b2082a5d0e826a46a312a88dfc8) defaulting to "local" if no git repo
> removes .git from build layer, emulates GH build

- backend/app/cmd/server.go
Fix for a bug potentially affecting #1139.
Before:
```
Content-Security-Policy: frame-ancestors domain1 domain2;
Content-Security-Policy: frame-ancestors domain1,domain2;
Unrecognized Content-Security-Policy directive 'domain2'.
```
After:
```
Content-Security-Policy: frame-ancestors domain1 domain2;
```
> Add missing env_delim to ALLOWED_HOSTS parameter

- frontend/app/components/auth/auth.spec.tsx
- frontend/app/components/auth/auth.tsx
- frontend/app/components/auth/auth.utils.ts
- frontend/app/components/comment-form/__subscribe-by-email/comment-form__subscribe-by-email.test.tsx
- frontend/app/components/comment-form/__subscribe-by-email/comment-form__subscribe-by-email.tsx
- frontend/app/store/user/actions.ts
Depends on #1396
Fixes the first part of #1393
Persist email in local storage for autofill in subscription popup.
> Fix email autofill in subscription popup

- frontend/app/components/root/root.tsx
Resolves #1340
Update the iframe's height when the image from a comment is loaded.
> Fix iframe height update on slow connection

- .github/workflows/ci-build.yml
- .github/workflows/ci-site.yml
- Dockerfile
- Dockerfile.artifacts
- Makefile
- backend/_example/memory_store/Dockerfile
- backend/app/store/service/service_test.go
- site/src/includes/components/head.njk
Previously we built a Docker image just for the test, but the introduction of multi-arch build in 9fbf0952 build also meant the push of the image, so it was restricted only to the master branch. This change re-introduces the Docker image build outside the master branch, which is helpful in pull requests.
We recently had a few frontend PRs which broke the Docker image build silently, and that change prevents it from happening.
> Return docker build for frontend and backend code outside in CI

- backend/app/rest/api/rest_private_test.go
- backend/app/store/comment.go
- site/src/docs/contributing/api/index.md
Previously it was sanitised using the HTML sanitiser, but it had proven troublesome and unnecessary. Remark42 rendered the markdown into proper HTML, but then some pieces of it (like cited HTML code inside the code block, marked by backticks) were cut out, which then showed the incorrect markdown to a user when they were editing the comment.
For example, the comment "\`foo\<bar\>\`" became "foo" after sanitising, and despite the proper render user saw only "foo" when editing the comment.
After this change, the initial comment markdown is preserved unaltered. It could contain dangerous HTML with JS, which I assume shouldn't be a problem as it's never rendered as HTML but instead supposed to be converted to HTML by the interpreter. In Remark42, it's stored in a comment.Text field and …
> Do not sanitise the original comment markdown

- .github/workflows/ci-build.yml
Currently, such a build most likely has access to secrets but fails due to the wrong username logging with DockerHub when rebase is done by anyone but @umputun.
> hardcode dockerhub username and ghcr.io repo for docker build

- site/src/docs/manuals/integration-with-gatsby/index.md
Some time ago Gatsby started to support Typescript natively. Also the frontend of remark42 is written in Typescript. So I thought it's a good idea to add a Typescript version of the component.
> docs(manuals): add ts version of react component

- backend/app/cmd/backup.go
- backend/app/cmd/cleanup.go
- backend/app/cmd/cmd.go
- backend/app/cmd/import.go
- backend/app/cmd/remap.go
- backend/app/cmd/restore.go
Timeout, admin password and site id are set in many commands, and we need to take care of synchronising the descriptions and flags between them.
This change moves these standard options to cmd.go importing them in the same manner CommonOpts imported by all commands already.
> Move common options to cmd.go

- backend/README.md
- frontend/apps/remark42/README.md
symlink for md files shows the doc right if they are placed there
https://github.com/umputun/remark42/tree/docs/link-frontend-dev-readme/frontend/apps/remark42
https://github.com/umputun/remark42/tree/docs/link-frontend-dev-readme/backend
> docs: link readme for frontend/backend dev

- backend/app/rest/api/rest_private.go
Current behavior on click on `http://127.0.0.1:8080/email/unsubscribe.html?site=remark&tkn=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdWQiOiJyZW1hcmsiLCJleHAiOjQ4MTI0ODAzNDMsImlzcyI6InJlbWFyazQyIiwibmJmIjoxNjU4ODgwMjgzLCJoYW5kc2hha2UiOnsiaWQiOiJkZXZfdXNlcjo6cGFza2FsLjA3QGdtYWlsLmNvbSJ9fQ.SFwJAS0fv39Bx_L59mVrIbvP0WzuEiUfY_0ROYvgNd0`:
```
remark42-dev  | 2022/07/26 20:17:51.490 [INFO]  {rest/middleware.go:63 rest.Recoverer.func1.1.1} request panic for /email/unsubscribe.html?site=remark&tkn=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdWQiOiJyZW1hcmsiLCJleHAiOjQ4MTI0ODAzNDMsImlzcyI6InJlbWFyazQyIiwibmJmIjoxNjU4ODgwMjgzLCJoYW5kc2hha2UiOnsiaWQiOiJkZXZfdXNlcjo6cGFza2FsLjA3QGdtYWlsLmNvbSJ9fQ.SFwJAS0fv39Bx_L59mVrIbvP0WzuEiUfY_0ROYvgNd0 from 172.20.0.1:58808, open unsubscribe.html.tmpl: no such file or …
```
> Fix unsubscribe template filename

- backend/app/cmd/server.go
Before that change, enabling Telegram auth also enabled Telegram user notifications.
> Don't enable telegram user notifications alongside auth

- backend/app/rest/api/rest.go
- backend/app/rest/api/rest_public.go
- backend/app/rest/api/rest_test.go
@umputun introduced that reference in 70649b271, but I can't find any references to it or the file itself now.
> Get rid of getstarted.html mentions

- .github/workflows/ci-frontend.yml
Currently, this step emits the "Error: No PR found. Only pull_request workflows are supported." message when run on the master branch commits (after the merge), so the change prevents it from being run there.
Resolves #1433.
> Do not run size limit job outside of PRs

- .github/workflows/ci-site.yml
Currently, such a build most likely has access to secrets but fails due to the wrong username logging with DockerHub when rebase and merge is done by anyone but @umputun.
I missed this one during #1436, which resulted in a site push error after @akellbl4 merged site-related PR in https://github.com/umputun/remark42/commit/86dae37c5d6f52893f99f0f896b6a809f22af160.
> Hardcode dockerhub username and ghcr.io repo for site docker push

- .github/workflows/ci-backend.yml
- Dockerfile
- Dockerfile.artifacts
- Makefile
- backend/app/store/engine/engine.go
It's a default in the presence of the vendor folder since Go 1.14, https://go.dev/ref/mod
> Remove mod=vendor from go build directives as it's no longer actual

- Dockerfile
I've updated everything to 1.9.2 but missed just one place. This PR fixes that.
> Bump buildgo to 1.9.2 to be consistent with other baseimage usages

- frontend/apps/remark42/app/utils/loadLocale.ts
I am so sorry that I forgot to commit loadLocale.ts in the last Traditional Chinese pull request, because there was a problem with my development environment at that time, husky would fail and I couldn't submit it correctly. After correct fix the problem, I forgot to add loadLocale.ts resulting in missing files.
I'm really sorry about my negligence.
> add lose commit Traditional Chinese locale file

- frontend/apps/remark42/app/utils/create-iframe.ts
In order to prevent problems like so https://github.com/umputun/remark42/pull/1421 we need to disable `color-scheme` for the iframe.
We can remove this line when support for `color-scheme` is implemented inside widget.
Issue for full support: https://github.com/umputun/remark42/issues/1430
> disable color-scheme on remark iframe

- frontend/apps/remark42/app/components/profile/profile.spec.tsx
- frontend/apps/remark42/app/components/profile/profile.tsx
- frontend/apps/remark42/package.json
- frontend/pnpm-lock.yaml
> fix: anon cannot request data removal

- .github/CODEOWNERS
This PR fixes the wrong directory name in CODEOWNERS file here: https://github.com/umputun/remark42/blob/master/.github/CODEOWNERS#L6
Signed-off-by: Avinal Kumar <avinal.xlvii@gmail.com>
> Fix directory name in CODEOWNERS file

- .dockerignore
- compose-dev-frontend.yml
Before that change, docker would create a new image on docker-compose file changes.
Frontend docker-compose file change removes options set to the same values as their default values.
> Add compose files to dockerignore, remove defaults from frontend compose

- backend/app/rest/api/rest.go
- backend/app/rest/api/rest_test.go
As discovered in #1477, dashes are expected to work in the site ID and do work everywhere but in email auth. That change makes the behaviour consistent: site ID now allows dashes.
Resolves #1477.
> Allow dashes in site ID when validating email auth request

- .github/workflows/e2e-tests.yml
- Dockerfile.artifacts
- Makefile
- site/src/docs/manuals/subdomain/index.md
Here are multiple changes to commands run by Makefile based on my attempts to run it on an Oracle Linux machine with the latest Docker.
The only known problem left is happening with `make bin`, `make dockerx` and `make release`:
```
[opc@terrty-net ~/remark42]$ make bin
Step 7/29 : RUN --mount=type=cache,id=pnpm,target=/root/.pnpm-store/v3 pnpm i
the --mount option requires BuildKit. Refer to https://docs.docker.com/go/buildkit/ to learn how to build images with BuildKit enabled
make: *** [Makefile:7: bin] Error 1
```
> Fix makefile and dockerfile

- frontend/apps/remark42/app/components/auth/auth.hooks.ts
- frontend/apps/remark42/app/components/root/root.tsx
- frontend/apps/remark42/webpack.config.js
Mutation observer was listening for all of the elements. When Auth dropdown appears it renders images and triggering height recalculations.
Resize trigger on image load was introduced in favor of resizing iframe for users with slow internet (when images load later and we need to resize iframe accordingly)
Solution:
Listen to mutations only on block with comments.
Plus remove unnecessary triggers.
> fix iframe resize on auth dropdown opening

- backend/app/cmd/server.go
- backend/app/store/service/service.go
Previously it was set to fixed strings, likely a test artefact.
Resolves #1499.
> Call admin store with a proper key

- .github/workflows/ci-backend.yml
- backend/.golangci.yml
- backend/app/main_test.go
- backend/app/rest/api/migrator.go
- backend/app/store/image/bolt_store_test.go
- backend/app/store/image/fs_store_test.go
- backend/app/store/service/service_test.go
Also, improve the goveralls installation method.
> Bump golangci-lint, fix discovered problems

- backend/_example/memory_store/server/data_test.go
- backend/app/store/engine/remote.go
- backend/app/store/engine/remote_test.go
Fixes the following conversion problem for BlockedUser:
```
panic: interface conversion:
interface {} is map[string]interface {}, not store.BlockedUser [recovered]
```
Resolves #1475.
> Fix RPC engine work with ListFlags method

- site/docker-compose.yml
- site/src/docs/manuals/subdomain/index.md
Previously, an image built for the `build` service was then used for `server`, and changes were invisible to the user before the container rebuild.
After that change, the useless static `build` service is deleted, Dockerfile is only used in the CI pipeline, and only the `server` service is left in docker-compose for the user to test and see documentation changes locally in real-time.
Resolves #1178
> Bump docker-compose.yml for the site to work with dev properly

- .github/workflows/ci-build.yml
Based on #1514 we know that build is not triggered anymore for tags, this is most likely the fix.
> Make docker build work on tag again

- frontend/apps/remark42/app/components/root/root.tsx
- frontend/apps/remark42/app/typings/global.d.ts
- site/src/docs/configuration/frontend/index.md
#1305
but I wasn't able to test that, because looks like this guide https://remark42.com/docs/contributing/frontend/ is outdated.
> Support no_footer option

- .github/workflows/ci-build.yml
- .github/workflows/ci-site.yml
Old ones produce warnings due to deprecation of NodeJS 12
> Bump github actions versions

- backend/app/migrator/backup.go
- backend/app/migrator/migrator.go
- backend/app/notify/notify.go
- backend/app/rest/api/admin.go
- backend/app/rest/api/rest_private.go
- backend/app/rest/api/rest_public.go
- backend/app/store/admin/admin.go
- backend/app/store/image/fs_store_test.go
- backend/app/store/service/tree_test.go
I haven't found a linter for these, so I had to catch these manually. I found #757 to fix one of these, and I thought it would be good to fix everything at once.
> Remove duplicate type definitions from function signatures

- backend/app/rest/api/ssl.go
This is not used since 1.17, https://github.com/golang/go/commit/9d0819b27ca248f9949e7cf6bf7cb9fe7cf574e8
> Prefer unused PreferServerCipherSuites param

- frontend/apps/remark42/app/components/comment-form/__field/comment-form__field.css
- frontend/apps/remark42/app/components/comment-form/comment-form.tsx
- frontend/apps/remark42/app/components/root/root.tsx
- frontend/apps/remark42/app/components/textarea-autosize.tsx
- frontend/apps/remark42/app/utils/post-message.ts
Addressing [this comment](https://github.com/umputun/remark42/issues/1521#issuecomment-1335241982)
`MutationObserver` doesn't spot some changes on textarea value changes (expecially on paste) so we add additional resize event on textarea size updates.
cc @damienalexandre
> update iframe size on textarea size change

- frontend/apps/remark42/app/__mocks__/resize-observer.ts
- frontend/apps/remark42/app/components/auth/auth.hooks.ts
- frontend/apps/remark42/app/components/comment-form/comment-form.tsx
- frontend/apps/remark42/app/components/root/root.tsx
- frontend/apps/remark42/app/components/textarea-autosize.tsx
- frontend/apps/remark42/app/utils/post-message.ts
- frontend/apps/remark42/jest.config.ts
Refactor resizing mechanism with more sutable browser API.
> refac: use resize observer instead of mutation observer

- frontend/apps/remark42/app/common/constants.ts
- frontend/apps/remark42/app/common/fetcher.ts
- frontend/apps/remark42/app/components/comment/comment.tsx
- frontend/apps/remark42/app/components/profile/profile.tsx
- frontend/apps/remark42/app/store/thread/utils.ts
- frontend/apps/remark42/app/utils/post-message.ts
- frontend/apps/remark42/templates/privacy.html
- frontend/apps/remark42/webpack.config.js
- site/src/docs/contributing/frontend/index.md
Also, little style changes in frontend development documentation and add a missing comma in the privacy policy.
> Fix typos in frontend code

- site/src/docs/manuals/spam/index.md
- site/src/docs/nav.json
It describes how anti-spam works now and its future.
Resolves #783.
> Add anti-spam documentation

- frontend/apps/remark42/app/common/settings.ts
- frontend/apps/remark42/app/components/auth/auth.hooks.ts
- frontend/apps/remark42/app/components/root/root.tsx
- frontend/apps/remark42/app/utils/post-message.ts
Pull the param from query and transform from string to boolean.
btw I don't know why do we have `remark_config` inside the iframe which is bad.
> fix: fix no footer param

- frontend/apps/remark42/app/typings/global.d.ts
- site/src/docs/configuration/frontend/index.md
Variables were documented in the documentation but not in the code, and max_last_comments needed to be documented.
Resolved #764.
> Improve frontend configuration parameters documentation

- site/src/docs/manuals/integration-with-astro/index.md
- site/src/docs/nav.json
In response to the discussion thread (#1556 ), here is a draft submission for an update to the docs for Astro w/Svelte integration.
> docs: added Astro w/Svelte Components Integration

- Dockerfile
Previously, the commands were combined incorrectly, and the failure of backend tests was ignored. Originally reported by @vdimir.
> Make docker build fail on backend test failure

- Dockerfile
- Dockerfile.artifacts
- frontend/packages/api/README.md
Previously version 8 was installed once it became available, breaking the pipelines and docker build.
> ping pnmp version to 7

- backend/app/rest/api/rest_private_test.go
- backend/app/store/comment.go
- backend/app/store/formatter.go
- backend/app/store/service/service.go
- backend/app/store/service/service_test.go
(url) is a text inserted by default and never an intended URL.
That additional validation will ensure that users won't post relative links because they are rarely intended.
This is how it looks without frontend changes:
Backend part for #809.
> Don't allow relative links in comments

- site/.eleventy.js
- site/src/styles.css
Anchor offset when navigating through an anchor.
It's now scrolling a bit further, to make a section-header also visible on the screen.
(Previously, selected section-header was hidden under the global page-header)
Unfortunately, I don't know how to get rid of the outline, when navigation through an anchor, as it's applied to the parent of styled element. The only way I see here - modify markdown-it-anchor sources (or use some different approach here)
> [site] fix: anchor offset

- frontend/apps/remark42/.size-limit.js
- frontend/apps/remark42/app/components/auth/auth.module.css
Issue #1622 
Changes:
- 1/1 aspect ratio
- white border around (for easier scan)
Before:
After:
> Telegram QR styling

- backend/app/cmd/server.go
- backend/app/rest/api/rest.go
- backend/app/rest/api/rest_test.go
- frontend/apps/remark42/app/__stubs__/static-config.ts
- frontend/apps/remark42/app/common/static-store.ts
- frontend/apps/remark42/app/common/types.ts
- frontend/packages/api/clients/public.ts
Bot username is returned as an answer to subscribe request, so knowing it in advance is unnecessary. Needed for #830.
> Switch from telegram_bot_username to telegram_notifications in /config endpoint

- site/src/docs/manuals/integration-with-astro/index.md
This pull request updates the [integration-with-astro.md](https://remark42.com/docs/manuals/integration-with-astro/) documentation to include a new example of how to integrate Remark42 with React/Preact components.
> docs: added Astro w/ React/Preact Components Integration

- backend/app/rest/api/rest_test.go
- backend/app/store/comment.go
- backend/app/store/comment_test.go
PR fixes the following issues with snippet generation for parent comments in RSS (couldn't find existing issues to tag them...):
1) Current implementation simply removes the last word, without truncating up to limit length.
2) In case if even the first word (e.g. magnet link or some base64) is too long don't add extra space.
STR:
1) Run dev version (https://remark42.com/docs/contributing/backend/)
2) Write very long comment (chatgpt helps :))
3) Reply to the comment
4) Check RSS
ER:
Text of original comment in reply item is truncated to 300 chars.
AR:
Only the last word is truncated.
> RSS: Fix snippet generation for parent comment

- site/src/docs/configuration/authorization/index.md
Update based on my experience going through them.
> Update Google auth setup instructions

- backend/app/main.go
It's not used aside from `server` but it was decided to keep it in place for backwards compatibility in PR #1544.
> Clarify SharedSecret usage by comment

- site/src/docs/manuals/subdomain/index.md
* Change Caddy example config to be compatible with Caddy V2 config format 
* Caddy V2 was released in 2020 and most new users are likely to be using that
* Existing config snippet is not compatible with V2 at all
> Update documentation to support Caddy V2

- backend/app/rest/api/rest_private.go
- backend/app/rest/api/rest_private_test.go
- backend/app/rest/api/rest_public_test.go
- backend/app/store/image/image.go
- backend/app/store/image/image_test.go
- backend/app/store/service/service.go
Previously, image proxying through API was not tested. The test is added here.
Previously, proxied and local images were checked for presence in the storage before previewing or posting the comment. That logic resulted in an inability to post with an image when a proxy for images is enabled,  as proxied images are not downloaded to disk before the first time someone loads them, which could only happen after the user either previews or posts the message.
After this change, preview and post only checks the local images' presence and ignore the proxied ones.
Resolves #1631.
> Fix preview and comment work with proxified images

- frontend/apps/remark42/app/components/comment-form/comment-form.tsx
- For preview errors, only `isErrorShown` is set to `true` and `errorMessage` is not provided. Hence the comment form shows `Something went wrong. Please try again a bit later.` (generic message) by default for all preview errors.
- Refactored the exception handling to derive error message from the response code (similar to `send` method). Now both Send and Preview shows the same error message.
Resolves: https://github.com/umputun/remark42/issues/1673
> Extract error message from API response for preview.

- backend/app/rest/api/rest_public_test.go
- backend/app/store/comment.go
- backend/app/store/comment_test.go
- backend/app/store/service/service_test.go
Previously, we stripped unsafe HTML tags but left some like `<a>`, but it's not expected to have a link in a title or user's name, so the new behaviour is stripping everything.
The issue was highlighted in #1677.
> Remove all HTML tags from comment title and username

- backend/app/cmd/server.go
- backend/app/cmd/server_test.go
- backend/app/rest/api/admin_test.go
- backend/app/rest/api/rest_public_test.go
- backend/app/store/service/service_test.go
- backend/app/store/service/title.go
- backend/app/store/service/title_test.go
Allowed domains consist of `REMARK_URL` second-level domain (or whole IP in case it's IP like `127.0.0.1`) and `ALLOWED_HOSTS`. That is needed to prevent Remark42 from asking arbitrary servers and storing the page title as the comment.PostTitle.
Previous behaviour allowed the caller of the API to create a comment with an arbitrary URL and learn the title of the page, which might be accessible to the server Remark42 is installed on but not to the user outside that network (CWE-918).
Resolves #1677.
> Limit TitleExtractor to allow only Remark42 whitelisted domains

- backend/app/main.go
- backend/app/rest/api/rest_private.go
As errors can be wrapped in recent versions of Go, the proper way to check the error types are `errors.As` and `errors.Is`.
> Fix wrapped errors checks

- frontend/apps/remark42/app/components/auth-panel/__column/auth-panel__column.css
- frontend/apps/remark42/app/components/auth-panel/__readonly-label/auth-panel__readonly-label.css
- frontend/apps/remark42/app/components/auth-panel/auth-panel.css
- frontend/apps/remark42/app/components/auth-panel/auth-panel.tsx
- frontend/apps/remark42/app/components/auth-panel/index.ts
> fix styles around admin controls

- backend/app/cmd/server.go
- backend/app/cmd/server_test.go
Previously, we extracted the second-level domain, but it doesn't make sense for a list of domains defined explicitly to display the comments.
Relates to #1677.
> Allow title extraction only from full match of AllowedHosts

- backend/app/migrator/commento.go
- backend/app/rest/api/migrator_test.go
- backend/app/rest/api/testdata/commento.json
Previously, top-level comments were incorrectly assigned parent comment id "root", which made them non-root, so they are not returned when requested in the `/find?format=tree` API call.
To fix the previously imported comments, please export all your comments and replace `"pid":"root"` with `"pid":""` and then re-import them.
Resolves #1696.
> Fix Commento top-level comments import

- backend/app/migrator/commento.go
- backend/app/migrator/testdata/commento.json
- backend/app/rest/api/migrator_test.go
- backend/app/rest/api/testdata/commento.json
- site/src/docs/backup/migration/index.md
Previously, it was not using the domain and relying on another export format.
Resolves #1697.
> Fix Commento import URL

- backend/app/cmd/server.go
- backend/app/migrator/wordpress.go
- backend/app/migrator/wordpress_test.go
- backend/app/rest/api/rest.go
- backend/app/rest/api/rest_private.go
- backend/app/rest/api/rest_private_test.go
- backend/app/rest/api/rest_public_test.go
- backend/app/store/formatter.go
- backend/app/store/formatter_test.go
- backend/app/store/service/service.go
- site/src/docs/configuration/parameters/index.md
It might be necessary if the comments should preserve original quotes instead of replacing them with angled ones.
Resolves #1666.
> Allow disabling fancy HTML formatting

- backend/_example/memory_store/accessor/image.go
- backend/_example/memory_store/accessor/image_test.go
- backend/_example/memory_store/server/image.go
- backend/_example/memory_store/server/image_test.go
- backend/_example/memory_store/server/rpc.go
- backend/app/store/image/bolt_store.go
- backend/app/store/image/bolt_store_test.go
- backend/app/store/image/fs_store.go
- backend/app/store/image/fs_store_test.go
- backend/app/store/image/image.go
- backend/app/store/image/image_mock.go
- backend/app/store/image/remote_store.go
- backend/app/store/image/remote_store_test.go
- backend/app/store/service/service.go
- backend/app/store/service/service_test.go
Previously, images were deleted only from comments deleted before EditDuration expiration. After this change, any deletion of the comment deletes images if they are not used elsewhere in comments under the same page.
FS store got a mutex lock to prevent missing the file in the transition from staging to permanent storage, which otherwise would result in the file being stuck in the permanent storage forever.
Resolves #1698.
> Cleanup images from deleted comments

- backend/app/cmd/backup_test.go
- backend/app/cmd/cmd.go
- backend/app/cmd/import_test.go
- backend/app/cmd/remap_test.go
- backend/app/rest/api/migrator.go
- backend/app/rest/api/migrator_test.go
- backend/app/rest/api/rss.go
- backend/remark.rest
Previously, status 200 was set for file export, which is used for backup, which resulted in an inability to set an error status code in case of a problem with file generation.
After this change, status code 200 would be written automatically by Go before we start writing the response's body.
Also, add meaningful error for lack of auth on import, remap and backup.
Previously, the error printed was just the following:
error response "401 Unauthorized", Unauthorized"
New error:
error response "401 Unauthorized", ensure you have set ADMIN_PASSWD and provided it to the command you're running: Unauthorized
> Fix lack of error on file site export, improve lack of ADMIN_PASSWD error message

- frontend/apps/remark42/app/components/comment/comment-actions.spec.tsx
- frontend/apps/remark42/app/components/comment/comment-actions.tsx
Resolves #1737. The user couldn't delete their comment once EditDuration passes.
> Hide delete button for non-admin users after edit period expires

- backend/app/cmd/server.go
It was set to string by mistake, proper type is token.Claims.
> Fix type for value for refresh token cache

- site/src/docs/configuration/parameters/index.md
According to [go-pkgz/notify's README](https://github.com/go-pkgz/notify?tab=readme-ov-file#email), you can actually put a name in front of the email address if you want to.
I've tested this on my instance, and it proved to work, so I thought people might want to know about this option.
> docs: Add email from examples

- .github/workflows/e2e-tests.yml
- frontend/Dockerfile.e2e
I accidentally broke the image and it was not tested. Now it would be latest stable and dockerfile change will trigger e2e tests to catch breaking like that.
> Switch playwright (e2e) to latest stable version

- backend/app/cmd/server.go
- site/src/docs/configuration/authorization/index.md
- site/src/docs/configuration/parameters/index.md
As mentioned in #1789, Apple login was broken in #1617.
I removed the problematic lines, recompiled a docker image, and confirmed the bug was indeed caused by the wrong `ResponseMode` params.
In addition, I've also improved some sections of docs about how to configure credentials used by Apple integration. One thing worth mentioning is that the term "Client ID" used by remark42 does not appear in Apple's developer dashboard but is used in [some documentation](https://developer.apple.com/documentation/sign_in_with_apple/request_an_authorization_to_the_sign_in_with_apple_server), which can cause some confusion. Therefore, I added an annotation indicating that the "Client ID" can be either "App ID" or "Service ID".
resolves #1789
> fix: Apple login integration

- frontend/apps/remark42/app/components/auth/auth.tsx
- frontend/apps/remark42/app/components/comment-form/comment-form.tsx
- frontend/apps/remark42/app/components/comment/comment.tsx
- frontend/apps/remark42/app/components/textarea-autosize.tsx
This pull request adds support for RTL (right-to-left) languages. By adding `dir=auto` to the relevant inputs, divs and textareas you get automatic support of RTL languages, with no detriment or loss in functionality to LTR languages.
See this excellent summary [PSA: Add dir="auto" to your inputs and textareas.](https://mough.xyz/312/psa-add-dir-auto-to-your-inputs-and-textareas)
**Before:**
**After:**
> add RTL support

- backend/go.mod
- backend/go.sum
- backend/vendor/github.com/go-pkgz/auth/README.md
- backend/vendor/github.com/go-pkgz/auth/provider/apple_pubkeys.go
- backend/vendor/github.com/go-pkgz/auth/token/jwt.go
- backend/vendor/modules.txt
The logout auth endpoint was returning no response body and type application/json which is not valid, this commit changes it to return plain/text instead which makes it valid.
Resolves https://github.com/umputun/remark42/issues/1812.
> Fix problem with logout button

- Dockerfile
This allows to not reinstall apk files when backend files change and the new image is built.
> Move gcc installation before backend files addition

- site/src/docs/contributing/translations/index.md
(`frontend/{path}` -> `frontend/apps/remark42/{path}`)
> docs: fix frontend paths in translation guide 

- backend/app/cmd/server.go
- backend/app/rest/api/rest.go
- backend/app/rest/api/rest_test.go
This is a security change. The policies I've added are not ideal but an improvement over lack of policies, and were tested by me for a few months to verify their work.
`Content-Security-Policy` now restricts resource loading and execution to enhance security:
- `default-src 'none'`: Disallow all resource loading by default.
- `base-uri 'none'`: Prevents the use of `<base>` tag to change the base URL for relative URLs.
- `form-action 'none'`: Disallows form submissions.
- `connect-src 'self'`: Restricts the origins that can be connected to (via XHR, WebSockets, etc.) to the same origin.
- `frame-src *`: Allow to be embedded on any domain.
- `img-src 'self'`: Allows images to be loaded only from the same origin. If `imageProxyEnabled` is true, allows images from any origin (`*`).
- …
> Add Content-Security-Policy and Permissions-Policy headers

- backend/app/rest/api/rest.go
- backend/app/rest/api/rest_test.go
Change the default img-src value to "*" and sets it to "'self'" when image proxy is enabled. The previous state was inversion of this logic which was wrong.
> Fix CSP img-src directive to allow everything without proxy

- backend/app/cmd/server.go
- site/src/docs/configuration/parameters/index.md
- site/src/docs/manuals/separate-domain/index.md
- site/src/docs/manuals/subdomain/index.md
This clarifies that the parameter sets CSP 'frame-ancestors' to limit hosts allowed to embed comments. The commit also improves the documentation on how to use ALLOWED_HOSTS with AUTH_SAME_SITE for different setup scenarios.
We might want to change AUTH_SAME_SITE to `strong` in v2.0 as it works on the subdomain of the same site as well as current Lax option.
> Clarify ALLOWED_HOSTS description and usage

- .github/workflows/ci-frontend-api.yml
- .github/workflows/ci-frontend.yml
- Dockerfile
- Dockerfile.artifacts
- frontend/Dockerfile.e2e
- frontend/apps/remark42/package.json
- frontend/package.json
- frontend/packages/api/README.md
- frontend/packages/api/package.json
- frontend/pnpm-lock.yaml
- site/src/docs/contributing/frontend/index.md
That suppose to help with Dependabot security updates not updating lockfile.
Size checks failing because it checks out old code version which doesn't allow pnpm v8.
> Update pnpm from v7 to v8

- frontend/.husky/pre-commit
Without this, installing and then deleting frontend dependencies leaves the developer unable to commit anything.
> Do not fail if frontend pre-commit hook fails

- site/package.json
- site/src/data/github.js
> Fix fetch module import so that latest release version would be shown on website

- docker-compose.yml
In discussion #1852 I realised that we don't have example with reverse proxy running outside of docker, this commit fixes that.
> Update docker-compose.yml with example for local reverse proxy

- .github/dependabot.yml
Examples should be updated alongside the backend directory and it makes no sense to have separate update PRs for it.
> Stop updating examples via dependabot

- backend/app/cmd/server_test.go
Previously, tmp boltdb was always created in directory 8080, example: https://github.com/umputun/remark42/actions/runs/12111878375/job/33764519442?pr=1857#step:5:84
> Fix server test configuration

- backend/app/cmd/server_test.go
- backend/app/main_test.go
- backend/app/rest/api/admin_test.go
- backend/app/rest/proxy/image_test.go
Based on my work on migration to jwt lib v5, moved to a separate PR.
> Improve tests

- backend/app/rest/api/rest_public.go
- backend/app/rest/api/rest_public_test.go
- backend/app/store/comment.go
- backend/app/store/service/tree.go
- backend/app/store/service/tree_test.go
- backend/remark.rest
`format=tree` pagination provides top-level comments with all replies and returns the last top-level comment as `last_comment` to be used as `offset` for the next page. If comments and replies overflow the limit, the one stepping out of the limit will not be returned. If the first comment and its replies after the given offset overflow the limit, it will be returned with all the replies.
`format=plain` pagination works by providing all comments and returning the last comment as `last_comment` to be used as `offset` for the next page.
Requires #1685 to be merged first. Backend part for #782.
> add pagination to GET /api/v1/find endpoint

- backend/app/migrator/commento.go
- backend/app/migrator/commento_test.go
- backend/app/migrator/migrator_test.go
- backend/app/migrator/testdata/commento.json
I added missing configuration for anonymous user. I think this should be enough to fix #1821
> Straightforward fix for importing anonymous comments from commento

- site/src/docs/configuration/notifications/index.md
Adds a table outlining a few other common variables that users may want to use when setting up webhook templating. Includes links to the full `struct`s in code as well. 
I setup notifications with ntfy and was having a hard time finding other variables available for templating besides just `Text`.
> Docs update describing available variables for webhook templating

- Makefile
- backend/_example/memory_store/compose-dev-memstore.yml
- compose-dev-backend.yml
- compose-dev-frontend.yml
- compose-e2e-test.yml
- docker-compose.yml
- site/src/docs/configuration/parameters/index.md
- site/src/docs/contributing/backend/index.md
- site/src/docs/getting-started/installation/index.md
- site/src/docs/manuals/kubernetes/index.md
- site/src/docs/manuals/reproxy/index.md
- site/src/docs/manuals/subdomain/index.md
This commit replaces all references to `umputun/remark42` Docker images on Docker Hub with `ghcr.io/umputun/remark42` from the GitHub Container Registry. It updates various Docker Compose files, documentation, and the Makefile to use the new image location. It also updates the kubernetes example to use the latest version.
Docker Hub is going to kill free pulls for too long by now.
> Migrate Docker images from Docker Hub to GitHub Container Registry

- .github/dependabot.yml
These have to be updated manually because there are always breaking changes.
> Disable dependabot automatic PRs for NPM modules

- backend/app/cmd/cleanup.go
- backend/app/cmd/server.go
- backend/app/migrator/disqus.go
- backend/app/notify/email_test.go
- backend/app/rest/api/admin_test.go
- backend/app/rest/api/migrator.go
- backend/app/rest/api/migrator_test.go
- backend/app/rest/api/rest_public.go
- backend/app/rest/api/rest_public_test.go
- backend/app/rest/api/rss_test.go
- backend/app/rest/proxy/image.go
- backend/app/store/comment.go
- backend/app/store/formatter.go
- backend/app/store/service/service.go
- backend/app/store/service/title.go
- Use strings.ReplaceAll
- Remove redundant internal structure names
> Automatic fix of errors reported by golangci-lint v2

- site/src/docs/configuration/telegram/index.md
- Added information about sending notifications to users, groups, and channels
- Documented that public group usernames can be used without @ symbol as IDs
- Clarified how to obtain IDs for different notification destinations
This addresses the question raised in discussion #1756 about using Telegram groups for notifications.
> docs: update Telegram configuration with group notification details

- backend/app/cmd/server.go
- frontend/apps/remark42/app/common/cookies.ts
- frontend/apps/remark42/app/common/fetcher.test.ts
- frontend/apps/remark42/app/common/fetcher.ts
- frontend/pnpm-lock.yaml
- site/src/docs/configuration/parameters/index.md
- When using AUTH_SEND_JWT_HEADER=true, the JWT token in header needed to be persisted to maintain login after page reload
- The frontend now properly handles JWT tokens received in headers by:
- Storing them in client-side cookies with the name 'JWT' to match what backend expects
- Extracting and storing the JWT ID as XSRF token in 'XSRF-TOKEN' cookie
- Setting cookies with Secure flag when on HTTPS connections
- Documentation has been updated to clarify that with this flag enabled, the frontend stores the JWT in a client-side cookie
First part of the fix for #1877, pre-requirement for fixing OAUTH login in #241
The issue was occurring because the JWT token was received in X-JWT header with AUTH_SEND_JWT_HEADER=true, but the token was only stored in memory. When the page reloaded, the …
> Fix login persistence with AUTH_SEND_JWT_HEADER enabled
