.dockerignore
Dockerfile

Dockerfile optimisations

---

.travis.yml

Remove extra lines from Travis CI config.

---

README.md
app/rest/api/admin.go
app/rest/api/admin_test.go
app/rest/auth/provider_test.go
app/store/comment.go
app/store/comment_test.go
app/store/engine/bolt_accessor.go
app/store/engine/bolt_accessor_test.go
app/store/engine/bolt_admin.go
app/store/engine/bolt_admin_test.go
app/store/engine/bolt_test.go
app/store/engine/engine.go

feature/delateuser - ability to remove all user data

---

app/rest/proxy/avatar.go
app/rest/proxy/avatar_store.go
app/rest/proxy/avatar_store_test.go
app/rest/proxy/avatar_test.go

Reduced avatar caching TTL to 7 days and fixed ETag generation.

add avatar caching #85

---

.gitignore
Dockerfile
web/.eslintrc.js
web/app/common/store.test.js
web/app/components/auth-panel/__tests__/auth-panel.test.js
web/app/components/auth-panel/auth-panel.jsx
web/app/components/preloader/__tests__/preloader.test.jsx
web/app/testUtils/index.js
web/babelOptions.js
web/fileTransformer.js
web/injectGlobalVariable.js
web/package-lock.json
web/package.json
web/webpack.config.js

I created setup for tests and write few tests on component and model.

Setup testing environment

---

backend/app/rest/api/admin_test.go
backend/app/store/engine/bolt_admin_test.go

increase ttl block in tests to reduce flakiness

---

web/app/components/comment/__info/comment__info.scss
web/app/components/comment/__link-to-parent/comment__link-to-parent.scss
web/app/components/comment/__time/comment__time.scss
web/app/components/comment/__username/comment__username.scss
web/app/components/comment/_view/_user/comment_view_user.scss

Fix comment_info block for small screens

---

web/.eslintrc.js
web/.prettierignore
web/.prettierrc.js
web/app/components/auth-panel/__tests__/auth-panel.test.js
web/app/components/auth-panel/auth-panel.jsx
web/app/components/blocked-users/blocked-users.jsx
web/app/components/comment/comment.jsx
web/app/components/input/input.jsx
web/app/components/list-comments/list-comments.jsx
web/app/components/preloader/__tests__/preloader.test.jsx
web/app/components/preloader/preloader.jsx
web/app/components/root/root.jsx
web/app/components/thread/thread.jsx
web/app/components/user-info/user-info.jsx
web/app/last-comments.js
web/app/remark.js
web/package-lock.json
web/package.json

Separate prettier-config for PR #117

Config for prettier + husky + lint-staged #92

---

web/app/common/polyfills.js
web/package-lock.json

replace promise polyfill from es6 to es7 #122

Issue #122

---

Dockerfile
README.md
web/package-lock.json
web/package.json

This allows to reuse docker fs layer with node_modules
in case if there were no changes in package*.json
As a result it decreases dependency on network and build times
in rebuilds at least in local environment.

reveal node_modules in separate container

---

README.md
backend/app/main.go
backend/app/migrator/disqus.go
backend/app/migrator/disqus_test.go
backend/app/migrator/migrator.go
backend/app/migrator/migrator_test.go
backend/app/migrator/wordpress.go
backend/app/migrator/wordpress_test.go
backend/app/rest/api/migrator.go
backend/app/rest/api/migrator_test.go
backend/scripts/import-wordpress.sh

Add wordpress importer

---

web/app/common/polyfills.js
web/app/components/comment/__action/comment__action.scss
web/app/components/comment/__control/comment__control.scss
web/app/components/comment/__controls/comment__controls.scss
web/app/components/comment/__vote/comment__vote.scss
web/app/components/input/__button/input__button.scss
web/app/components/root/__show-more/root__show-more.scss
web/app/embed.js
web/iframe.html
web/package-lock.json
web/package.json

1. Added focus-visible polyfill
2. Removed unnecessary `outline: none` from styles
3. Made buttons Pin, Block, Delete visible under focus

Add focus-visible polyfill, issue #187

---

web/app/deleteme.js

getUser api call added to check whether user is admin or not

Auth handling added to deleteme.html #170

---

README.md
backend/app/cmd/server.go
backend/app/store/service/service.go
backend/app/store/service/service_test.go

feel free to correct me if I did something not as expected

added maximum votes limit per comment

---

backend/app/rest/api/rest_test.go

Added two tests for `api` package. It checks Static mode and partially autocert mode (http only, without checking integration with le)
relates to #191

add tests for ssl mode

---

web/app/components/comment/__vote/_disabled/comment__vote_disabled.scss

It disables hover color change for not logged in users.

Prioritize disabled arrows style over general

---

README.md

As far as I understand, this line wasn't updated during the merge of #197 . Or I'm missing something here?

Inconsistency through README.md

---

web/index.ejs

To https://github.com/umputun/remark/issues/261#issuecomment-457727198
Added widgets to demo page:

add widgets to demo page

---

README.md

Just a little note about demo page (right now can't be found anywhere except sources)

add info about /web demo page

---

README.md
web/app/components/comment/comment.jsx

To #260 
Disables voting below 0, and removes score sign if `POSITIVE_SCORE=true`

Support positive score only mode

---

README.md
web/.babelrc
web/app/common/api.ts
web/app/common/types.ts
web/app/components/comment/comment.test.tsx
web/app/components/comment/comment.tsx
web/app/components/root/root.tsx
web/webpack.config.js

to #297 
Adds ui support for new voting api.
Backend side doesn't seem to work, `vote` is always 0.

support new voting api in ui

---

web/app/common/api.ts
web/app/common/fetcher.ts
web/app/common/static_store.ts
web/app/common/types.ts
web/app/components/comment/comment.tsx
web/app/components/comment/connected-comment.ts
web/app/components/input/_theme/_dark/input_theme_dark.scss
web/app/components/input/input.tsx
web/app/components/input/textarea-autosize.tsx
web/app/components/root/root.tsx
web/app/utils/replaceSelection.ts
web/app/utils/sleep.ts

Adds ui support for #285
Somehow even delay of 1500ms still hits rate limiter, anyway I set 5s delay between Image uploads, looks kinda reasonable.

Image upload ui

---

web/.eslintrc.js
web/app/common/fetcher.test.ts
web/app/common/fetcher.ts
web/app/utils/errorUtils.ts

Adds handling of `401`, `403`, `429` rest codes in ui.

Handle specific rest status codes in fetcher

---

frontend/app/common/api.ts
frontend/app/deleteme.ts

Fix "delete me" feature

---

frontend/app/components/comment/comment.tsx
frontend/app/components/comment/connected-comment.ts
frontend/app/components/root/root.tsx

to #346 
Apparently not only preview was broken, but image upload too :-)
I missed the thing that I was trying to connect functions which are not `actions`, but straight api calls via react-redux `connect`.

Fix ui errors (preview and image upload)

---

frontend/app/store/sort/actions.ts

Fix sorting change makes hidden users to appear

---

frontend/app/components/comment/_level/comment_level.scss
frontend/app/components/comment/_theme/_dark/comment_theme_dark.scss
frontend/app/components/comment/styles.ts
frontend/app/components/thread/_theme_dark/thread_theme_dark.scss
frontend/app/components/thread/index.ts
frontend/app/components/thread/thread.scss
frontend/app/components/thread/thread.tsx

as a continuation of #350
* lines became dotted
* levels higher than 5 are unindented

Ui threads minor

---

frontend/app/components/input/input.tsx

to https://github.com/umputun/remark/issues/138#issuecomment-507052348

add spellcheck attribute

---

frontend/app/components/comment/__controls/comment__controls.scss

fix: controls not visible on mobile because it doesn't have hover

---

frontend/app/components/auth-panel/__email-login-form/auth-panel__email-login-form.scss

to https://github.com/umputun/remark/issues/349#issuecomment-508960807

Increase margins in email auth popup

---

frontend/app/components/auth-panel/__email-login-form/auth-panel__email-login-form.tsx
frontend/app/components/dropdown/dropdown.tsx

Added some modifications to dropdown component
* it expands iframe height if dropdown content doesn't fit
* it shifts horizontally if placed behind iframe window bounds

Dropdown modifications

---

frontend/app/components/input/input.tsx

The PR is changing a label in editing form, closing #369

Change label in editing form from Edit to Save

---

frontend/app/components/input/__markdown-toolbar/input__markdown-toolbar.scss
frontend/app/components/input/input.tsx
frontend/app/components/input/markdown-toolbar-icons/image-icon.tsx
frontend/app/components/input/markdown-toolbar.tsx

Add a button for image upload

---

frontend/app/store/comments/utils.ts
frontend/app/store/user/actions.ts

to https://github.com/umputun/remark/issues/377#issuecomment-514307418 😬

Fix unblocking after page refresh

---

Dockerfile
backend/app/rest/api/rest_public.go
backend/app/store/engine/bolt.go
backend/app/store/engine/bolt_test.go
backend/app/store/service/service.go
backend/app/store/service/service_test.go

Add support of `since` parameter to /find request(s)

Find since

---

frontend/app/components/auth-panel/__dropdown-provider/auth-panel__dropdown-provider.scss
frontend/app/components/auth-panel/auth-panel.test.tsx
frontend/app/components/auth-panel/auth-panel.tsx
frontend/app/components/auth-panel/index.ts
frontend/app/components/dropdown/__item/dropdown__item.scss
frontend/app/components/dropdown/_active/dropdown_active.scss
frontend/app/components/dropdown/dropdown.tsx
frontend/app/components/root/root.tsx
frontend/app/remark.tsx
frontend/app/store/actions.ts
frontend/app/store/comments/reducers.ts
frontend/app/store/index.ts
frontend/app/store/provider/actions.ts
frontend/app/store/provider/reducers.test.ts
frontend/app/store/provider/reducers.ts
frontend/app/store/provider/types.ts
frontend/app/store/reducers.ts
frontend/app/store/thread/actions.ts
frontend/app/store/thread/reducers.ts
frontend/app/store/thread/types.ts
frontend/app/store/user-info/reducers.ts
frontend/app/store/user/actions.ts
frontend/app/store/user/reducers.ts

to #382 
Adds hiding of login providers on window resize

Auth login design

---

frontend/app/components/auth-panel/auth-panel.scss

to https://github.com/umputun/remark/pull/390#issuecomment-515300851

Fix auth panel columns vertical alignment

---

frontend/app/components/auth-panel/auth-panel.test.tsx
frontend/app/components/auth-panel/auth-panel.tsx

Messed up a bit and missed case where last login provider not found.

fix auth panel providers sorting

---

frontend/app/components/auth-panel/__select-label-value/auth-panel__select-label-value.scss
frontend/app/components/auth-panel/auth-panel.test.tsx
frontend/app/components/auth-panel/auth-panel.tsx
frontend/app/components/auth-panel/index.ts
frontend/app/components/comment/comment.test.tsx
frontend/app/components/preloader/preloader.test.tsx
frontend/app/testUtils/index.ts

Some minor things:
* removed custom test renderer in favor of enzyme's one
* #389

Minor things

---

README.md

Fix description of "image.type"

Small fix of README.md

---

README.md
frontend/app/counter.ts
frontend/app/embed.ts

As a continuation of https://github.com/umputun/remark/issues/413

Change default post url to window.location.origin + window.location.pathname

---

.github/workflows/blank.yml

- Fix problem with optional environment variable `DEBUG`
- Add case for tags and branches

Fix problem with DEBUG variable

---

frontend/app/components/input/_theme/_dark/input_theme_dark.scss

Resolving #452 Dark theme shows white preview.
Hello! Please try and check that implementation.
@umputun @Reeywhaar

Dark theme shows white preview #453

---

README.md

- Add href for new paragraph in README.md

Add href for new paragraph in README.md

---

backend/app/notify/email_test.go
backend/app/rest/api/rest_private_test.go

Improve email notifications tests coverage

---

backend/app/store/engine/bolt_test.go
backend/app/store/service/service_test.go

Add unit tests for service operations with user details

---

backend/app/rest/api/rest_test.go

Similar to #506, fix following detected false positive failures:
| [TestRest_RunStaticSSLMode](https://github.com/umputun/remark/blob/51c64f00e56ca97d8641d0202f9336bc393e5ac8/backend/app/rest/api/rest_test.go#L102) | [Oct 19](https://github.com/umputun/remark/runs/266854607#step:5:523) |
| [TestRest_RunStaticSSLMode](https://github.com/umputun/remark/blob/4576c4cdd1c29d153bff2cf7391ce427c8b3e7ed/backend/app/rest/api/rest_test.go#L102) | [Dec 11](https://github.com/umputun/remark/commit/4576c4cdd1c29d153bff2cf7391ce427c8b3e7ed/checks?check_suite_id=352755386#step:5:390) |
Error reason in the log:
{api/rest.go:114 api.(*Rest).Run.func1} http redirect server terminated, listen tcp :38080: bind: address already in use

fix "address is already in use" for TestRest_RunStaticSSLMode and TestRest_RunAutocertModeHTTPOnly

---

backend/app/migrator/disqus_test.go
backend/app/migrator/migrator_test.go
backend/app/migrator/native_test.go
backend/app/migrator/wordpress_test.go
backend/app/rest/api/migrator_test.go
backend/app/rest/api/rest_test.go
backend/app/store/service/service_test.go

$subj, here is my best shot at the problem. If\when it will happen next time, I'll investigate and improve over the current solution.
Overall tests (especially Migrator* ones) should become more reliable after this PR.

Improve TestMigrator_* tests reliability

---

Dockerfile
backend/app/cmd/server_test.go
backend/app/main_test.go
backend/app/migrator/backup_test.go
backend/app/migrator/disqus_test.go
backend/app/migrator/native_test.go
backend/app/migrator/wordpress_test.go
backend/app/notify/notify_test.go
backend/app/rest/api/admin_test.go
backend/app/rest/api/rest_private_test.go
backend/app/rest/api/rest_public_test.go
backend/app/rest/api/rest_test.go
backend/app/store/engine/bolt_test.go
backend/app/store/image/image_test.go
backend/app/store/service/service_test.go

Address [this issue](https://github.com/umputun/remark/pull/447/checks?check_run_id=368368898#step:5:253) plus adjust tests to work on HDD out-of-the-box.

Adjust tests timouts to work on machine with HDD

---

backend/app/store/service/service_test.go

Make TestService_CreateFromPartialWithTitle offline friendly

---

frontend/app/components/auth-panel/__email-login-form/auth-panel__email-login-form.tsx

<details>
<summary>Bug</summary>
</details>
<details>
<summary>Solve</summary>
</details>
Solve: clear error state before next try

Hide error after repeated request in email login form

---

Dockerfile
Dockerfile.artifacts
backend/app/notify/notify_test.go

- remove empty lines from Dockerfile
- improve TestService_WithDrops output on failure

Small fixes

---

frontend/app/components/comment/comment.test.tsx
frontend/app/components/comment/comment.tsx

It happened because `this.setState` was used in `constructor`
<details>
<summary>Warnings</summary>
</details>

Fix warnings in comment.tsx component

---

frontend/.prettierrc
frontend/deleteme.html
frontend/iframe.html
frontend/last-comments.ejs
frontend/tsconfig.json

It just formatted frontend files on the right way.

Run prettier on all files

---

frontend/index.ejs

Theme of UI is changing follows to OS settings.
I made just for demo page.

Add auto-changing theme for demo page

---

frontend/package-lock.json
frontend/package.json

The building dep was updated. It does not affect final code.
<details>
<summary>Problem</summary>
</details>
<details>
<summary>Updated package</summary>
Link: https://webpack.js.org/plugins/copy-webpack-plugin/
Description: _Copies individual files or entire directories, which already exist, to the build directory._
</details>

Update vulnerable dependency

---

frontend/app/components/comment/__body/comment__body.scss
frontend/app/components/comment/__info/comment__info.scss
frontend/app/components/comment/_collapsed/comment_collapsed.scss
frontend/app/components/comment/_view/_user/comment_view_user.scss
frontend/app/components/comment/comment.scss
frontend/app/components/comment/comment.tsx
frontend/app/components/comment/connected-comment.tsx
frontend/app/components/thread/__collapse/thread__collapse.scss
frontend/app/components/thread/_theme_dark/thread_theme_dark.scss
frontend/app/components/thread/index.ts
frontend/app/components/thread/thread.scss
frontend/app/components/thread/thread.tsx

Collapse comment by thread border

---

README.md
backend/app/notify/email.go

Update email templates

---

frontend/app/components/comment/__score/comment__score.scss
frontend/app/components/raw-content/raw-content.scss

*  fix score position
* add margin before blockquote if it is placed after text

Fix score position and margin before blockquote

---

backend/app/notify/email.go

Fix ParentCommentDate in email template

---

frontend/app/components/comment/comment.tsx

to #565
Stop rendering dummy block for comment once it appears in viewport

Do not render dummy for comment once it gets into viewport

---

frontend/app/components/thread/thread.tsx

https://github.com/umputun/remark/pull/545#discussion_r366275278

Add shallow equality

---

frontend/app/components/comment/_replying/comment_replying.scss
frontend/app/components/comment/comment.scss

Fix bugs in mobile view in reply mode

---

backend/app/store/image/fs_store.go

Resolve [this review comment](https://github.com/umputun/remark/pull/447/files/e7f9225858da173c22340366271d163f611ae21f#diff-e4370583473f110ef9804344e03c7ae7).

clarify FileSystem.Save code

---

.gitignore
frontend/app/components/raw-content/_theme/_dark/raw-content_theme_dark.scss
frontend/app/components/raw-content/_theme/_light/raw-content_theme_light.scss
frontend/app/remark.tsx
frontend/app/styles/code-highlight.scss

This PR includes #590, fixes #32.
I added CSS for code coloring for both light and dark themes in solarized scheme with small changes.
If you have suggestions connected with colors of highlighting welcome to comments.

Code colors

---

frontend/app/components/raw-content/code-highlight.scss
frontend/app/components/raw-content/index.ts
frontend/app/components/raw-content/raw-content.scss
frontend/app/remark.tsx

Add styles for `code` element

---

frontend/app/components/raw-content/_theme/_dark/raw-content_theme_dark.scss
frontend/app/components/raw-content/_theme/_light/raw-content_theme_light.scss
frontend/app/components/raw-content/code-highlight.scss
frontend/app/components/raw-content/raw-content.scss

* quote with left border and without background
* style for old code insetions (structure pre > code)
* unified elemets margins
* 1px separator height
Compare:
Fixed old code insertions:

Small restyling of comment elements

---

frontend/.size-limit.js
frontend/app/components/comment-form/index.ts
frontend/app/components/comment/comment.test.tsx
frontend/app/components/comment/comment.tsx
frontend/app/components/list-comments/list-comments.tsx
frontend/app/components/root/root.tsx
frontend/app/components/thread/thread.tsx
frontend/app/components/user-info/last-comments-list.tsx

I pass comment form as prop, because CommentForm don't need for last comment widget.

Optimize last comment widget

---

frontend/app/components/comment-form/__actions/comment-form__actions.scss
frontend/app/components/comment-form/__rss/comment-form__rss.scss
frontend/app/components/comment-form/comment-form.tsx

Related issue #607 
<details>
<summary>IPhone X</summary>
</details>
<details>
<summary>Pixel 2</summary>
</details>
<details>
<summary>MDPI screen</summary>
</details>

fix markup for subscribe block for long description

---

backend/app/cmd/server.go
backend/app/cmd/server_test.go

set anonymous with admin names to blocked 

---

docs/README.md
docs/subdomain.md

[Thanks](https://github.com/umputun/remark42/issues/26#issuecomment-596057598) to @dukangxu we now have an example of caddy configuration for remark.
[Rewritten doc render](https://github.com/umputun/remark42/blob/17a18e7f41b5a83b9c63440e5e34ab216c949d45/docs/subdomain.md) for reviewer.

Add caddy documentation

---

frontend/app/@types/global.d.ts
frontend/app/common/fetcher.test.ts
frontend/app/store/comments/actions.test.ts
frontend/app/store/comments/actions.ts
frontend/app/store/comments/utils.test.ts
frontend/app/store/comments/utils.ts
frontend/app/testUtils/index.ts
frontend/app/testUtils/mockHeaders.ts
frontend/jest.config.js
frontend/package-lock.json
frontend/package.json

@grayru reported a problem with saving of comments sorting in the last episode of a famous podcast. 
I fixed the problem and added tests for it.

Fix saving of comment sorting

---

frontend/app/common/local-storage.test.ts
frontend/app/common/local-storage.ts
frontend/app/components/comment-form/comment-form.test.tsx
frontend/app/components/comment-form/comment-form.tsx
frontend/app/components/comment/comment.tsx

Resolving #630 
* add functions for saving JSON to local storage and tests
* remove a comment from local storage after posting

Fix clear localstorage after comment sending

---

.github/workflows/ci-test-backend.yml
backend/_example/memory_store/go.mod
backend/app/notify/telegram_test.go
backend/go.mod
backend/vendor/modules.txt

switch to go 1.14 

---

frontend/app/components/comment-form/__subscribe-by-email/comment-form__subscribe-by-email.tsx

<details>
<summary> Bug </summary>
</details>
<details>
<summary> After fix</summary>
</details>

Fix back button in email subscription form

---

README.md
docs/README.md
docs/translation.md
frontend/Readme.md

Add instructions for adding new translations. Resolves #10.
[Rendered document](https://github.com/umputun/remark42/blob/a359c7a8c357b29f54ef1a78156ee70872b7b1f1/docs/translation.md) to review.
//cc @Ksinia for review.

Add translation instructions

---

frontend/app/components/comment/_theme/_dark/comment_theme_dark.scss
frontend/app/components/comment/_theme/_light/comment_theme_light.scss
frontend/app/components/root/root.tsx

Resolves #559
Adds .comment_highlighting class after scrolling to comment.

Highlight comment when user went to it by link

---

frontend/app/components/comment/comment.scss

as @akellbl4 suggested in https://github.com/umputun/remark42/pull/660

Adds background transition to .comment class

---

backend/app/rest/api/rest_public_test.go
backend/app/rest/api/rest_test.go

This might help not to catch race condition in tests.

Don't use cache in rest tests which don't utilize it

---

backend/_example/memory_store/accessor/image.go
backend/_example/memory_store/accessor/image_test.go
backend/_example/memory_store/server/image.go
backend/_example/memory_store/server/image_test.go
backend/_example/memory_store/server/rpc.go
backend/app/cmd/server.go
backend/app/rest/api/rest_private_test.go
backend/app/rest/api/rest_test.go
backend/app/store/image/bolt_store.go
backend/app/store/image/bolt_store_test.go
backend/app/store/image/fs_store.go
backend/app/store/image/fs_store_test.go
backend/app/store/image/image.go
backend/app/store/image/image_mock.go
backend/app/store/image/image_test.go
backend/app/store/image/remote_store.go
backend/app/store/image/remote_store_test.go
backend/app/store/service/service.go
backend/app/store/service/service_test.go

Resolves #584. Relies on merging #692 first.
1. Set `EDIT_TIME=20s` in docker-compose.yml
2. Start dev instance using docker-compose, post comment with image
3. Restart docker-compose
4. Wait for 2 minutes
5. Reload the page: image from the comment is no longer available as it was stuck in Staging without commit and then was deleted after `EDIT_TIME*5`, `1m40s` in this case.
1. Set `EDIT_TIME=20s` in docker-compose.yml
2. Start dev instance using docker-compose, post comment with image
3. Restart docker-compose
4. Wait for 2 minutes
5. Reload the page: image is still in place

Image commit on start

---

backend/.golangci.yml
backend/_example/memory_store/accessor/data.go
backend/app/cmd/cleanup.go
backend/app/cmd/server_test.go
backend/app/main.go
backend/app/migrator/disqus.go
backend/app/migrator/native.go
backend/app/migrator/native_test.go
backend/app/migrator/wordpress.go
backend/app/notify/notify_test.go
backend/app/notify/telegram.go
backend/app/rest/api/migrator.go
backend/app/rest/api/rest_private_test.go
backend/app/rest/api/rest_public_test.go
backend/app/rest/api/rest_test.go
backend/app/rest/api/rss_test.go
backend/app/store/admin/admin.go
backend/app/store/admin/remote.go
backend/app/store/engine/bolt.go
backend/app/store/image/bolt_store.go
backend/app/store/image/bolt_store_test.go
backend/app/store/image/fs_store.go
backend/app/store/image/image.go
backend/app/store/image/remote_store.go
backend/app/store/service/restricted_words.go
backend/app/store/service/service.go
backend/app/store/service/service_test.go
backend/app/store/service/tree.go
backend/app/store/user.go

$subj, multiple checks are hard to fix and I just disabled them for now.

Enable gocritic linter and fix found issues

---

frontend/app/components/root/root.tsx

Open hidden thread and jump to linked comment 

---

frontend/package-lock.json
frontend/package.json

Update frontend dev dependencies

---

backend/app/store/service/service.go
backend/app/store/service/service_test.go

Addresses the bug preventing correctional voting if same-ip check turned on

---

backend/_example/memory_store/go.sum
backend/go.mod
backend/go.sum
backend/vendor/github.com/go-pkgz/lcw/README.md
backend/vendor/github.com/go-pkgz/lcw/cache.go
backend/vendor/github.com/go-pkgz/lcw/eventbus/pubsub.go
backend/vendor/github.com/go-pkgz/lcw/eventbus/redis.go
backend/vendor/github.com/go-pkgz/lcw/expirable_cache.go
backend/vendor/github.com/go-pkgz/lcw/go.mod
backend/vendor/github.com/go-pkgz/lcw/go.sum
backend/vendor/github.com/go-pkgz/lcw/lru_cache.go
backend/vendor/github.com/go-pkgz/lcw/options.go
backend/vendor/modules.txt

This is necessary to add the distributed cache support.

bump go-pkgz/lcw to v0.7.1

---

README.md

According to https://github.com/umputun/remark42/issues/737, actually.

update README according to #737

---

.github/workflows/ci-test-frontend.yml
frontend/.huskyrc.js

Is there any reason to run FE specs on local ENV instead of run them on CI?

Run FE specs on CI

---

README.md
frontend/app/common/config-types.ts
frontend/app/common/settings.ts
frontend/app/components/comment-form/comment-form.tsx

Hide email subscription by param from frontend

---

backend/app/cmd/server_test.go
backend/app/rest/api/rest_test.go

Refactoring before implementing search (see #757)

---

.github/workflows/ci-test-frontend.yml
frontend/webpack.config.js

master:
https://github.com/pustovalov/remark42/actions/runs/224388470
time: 1m 57s
```
NODE_ENV = production
REMARK_ENV = https://demo.remark42.com
Hash: 70ab29f80338d139455d
Version: webpack 4.43.0
Time: 37223ms
```
this PR:
https://github.com/pustovalov/remark42/actions/runs/224440717
time: 1m 32s 
```
NODE_ENV = production
REMARK_ENV = https://demo.remark42.com
Hash: 70ab29f80338d139455d
Version: webpack 4.43.0
Time: 19360ms
```

make FE CI more parallel

---

.github/workflows/ci-test-frontend.yml
frontend/package-lock.json

0/50 failed:
https://github.com/pustovalov/remark42/actions?query=branch%3Afe-ci-lock-test+workflow%3Atest_frontend

Make FE CI more stable

---

.github/workflows/ci-test-frontend.yml
README.md
frontend/codecov.yml
frontend/jest.config.js
frontend/package-lock.json
frontend/package.json

Example:
https://codecov.io/gh/pustovalov/remark42/branch/fe-cov-1
To do:
setup `CODECOV_TOKEN` to gh-actions ENV variables, link https://codecov.io/gh/umputun/remark42/settings

Setup coverage for FE

---

README.md
docs/1.6/subdomain.md
docs/latest/subdomain.md

use correct case for GitHub mentions

---

frontend/app/components/comment-form/comment-form.test.tsx
frontend/app/components/comment-form/comment-form.tsx

Fix max length counter on comment field in Safari

---

frontend/app/components/comment-form/__subscribe-by-rss/comment-form__subscribe-by-rss.test.tsx
frontend/app/components/comment-form/__subscribe-by-rss/comment-form__subscribe-by-rss.tsx

Params of the RSS subscription URL were messed up. This PR fixes that.

Fix RSS links

---

README.md

Resolves #821, kudos to @uPagge for discovery.

readme: fix SPA link, web config syntax

---

frontend/app/common/constants.ts
frontend/app/common/fetcher.ts
frontend/app/store/user/actions.ts

1. If X-JWT header received by any response - it will be stored in localstorage
2. If jwt is in localstorage - it will be send by each request
3. If 403 received and jwt in localstorage - it will be removed.

#819 Added jwt token to requests

---

README.md

Fix environment var table

---

Dockerfile.artifacts
docker-init.sh

Forgot to add replace via `sed` in new js bundles

add mjs for sed

---

frontend/app/components/user-info/last-comments-list.tsx

add missing Fragment import

---

frontend/app/common/fetcher.test.ts
frontend/app/common/fetcher.ts

Do not send Content-Type on file upload

---

frontend/app/common/api.ts

Fix "remove comment" action for a user

change fetcher for user delete comment action

---

frontend/app/__mocks__/localstorage.ts
frontend/app/typings/jest-localstorage-mock.d.ts
frontend/jest.config.js

Clear localstorage-mock after each test

---

frontend/app/hooks/useAction.ts

While developing a new auth found an unused hook in the frontend folder.

remove unused hook

---

frontend/package-lock.json
frontend/package.json
frontend/webpack.config.js

- add @prefetch/babel-plugin for hot replacement with preact/hooks
- fix config for hop replacement
- remove optimization config that does nothing
- use the modern build in development (with two versions hot replacement won't work)
- remove commented html-webpack-plugin part
Separated from #844

fix webpack config

---

frontend/app/components/auth/auth.hooks.ts

**Problem**
When open auth dropdown it's cut off by iframe with small height.
**Bug**
On dropdown open, we should change iframe height but we don't.
**Solve**
* change iframe height on content change
* change iframe size on dropdown open
Resolves #910

Fix dropdown opening

---

frontend/app/components/auth/auth.spec.tsx
frontend/app/components/auth/auth.tsx

Fix situation when a token is invalid and the error message doesn't appear
- convert arrow funcs to named funcs (improve debugging experience and readability)
- add more test cases
- rewrite tests in the recommended way and add more cases coverage by the lib

Fix error message on token tab on login

---

README.md

We added `mjs` chunks for modern browsers and we should update instructions for that.

Update README.md for v1.7

---

frontend/app/components/auth/auth.spec.tsx
frontend/app/components/auth/auth.tsx

Resolve #957
Change actually quite simple. Allow spaces in the input and trim spaces on blur.

allow spaces in username with trim

---

frontend/package-lock.json
frontend/package.json
frontend/webpack.config.js

Add minification for the CSS files.
public/remark.css                 9.42 KB (-6.47% 🔽)
public/last-comments.css   5.05 KB (-11.74% 🔽)

minify css bundle

---

frontend/app/components/avatar/avatar.spec.tsx
frontend/app/components/avatar/avatar.tsx
frontend/app/components/comment/comment.tsx
frontend/app/components/user-info/user-info.tsx
frontend/app/typings/svg.d.ts

Discussed few points with @Mavrin in dm and decided to make changes on it.

avatar fixes after review

---

README.md

Update import documentation, move it to doc from the readme

---

backend/app/cmd/server.go

I was not careful enough when introducing the new option for Telegram, this PR fixes that.

Fix telegram token server setting

---

README.md
frontend/README.md
site/README.md

* Update links
* Update table of contents
* Improve the design
* Improve formatting
* Fix abbreviations and proper names
* Fix tables
* Fix indentation in code snippets
* Fix typos

Improve README

---

site/src/pages/index.md

Synchronize the project description with the description from the repository.

Update information in `index.md`

---

frontend/package-lock.json
frontend/package.json
frontend/webpack.config.js

- minify all css after build parts
- use css nano for old css files

optimize css

---

frontend/app/last-comments.tsx

...because it handled by webpack

Disable injection of last-comments.css in dev

---

backend/app/cmd/server.go
backend/app/cmd/server_test.go

Fix for https://github.com/go-pkgz/auth/issues/90

Run missing Telegram auth goroutine

---

site/src/includes/components/header.njk

open [releases](https://github.com/umputun/remark42/releases) page by click on the version in the header

set releases link on version in header

---

site/src/docs/configuration/email/index.md

Clarification of email documentation.

clarify user and admin email instructions

---

frontend/app/components/profile/profile.module.css
frontend/app/components/profile/profile.spec.tsx
frontend/app/components/profile/profile.tsx
frontend/app/locales/be.json
frontend/app/locales/bg.json
frontend/app/locales/bp.json
frontend/app/locales/de.json
frontend/app/locales/en.json
frontend/app/locales/es.json
frontend/app/locales/fi.json
frontend/app/locales/fr.json
frontend/app/locales/ja.json
frontend/app/locales/ko.json
frontend/app/locales/pl.json
frontend/app/locales/ru.json
frontend/app/locales/tr.json
frontend/app/locales/ua.json
frontend/app/locales/vi.json
frontend/app/locales/zh.json

PR for https://github.com/umputun/remark42/issues/1084
Error:
Loading:

Update UI for user comments sidebar

---

backend/app/store/service/service_test.go

Supposedly fixes https://github.com/umputun/remark42/runs/3514301671?check_suite_focus=true#step:6:50

Don't use "t" inside assert.Eventually

---

backend/app/store/service/service_test.go

Fixes:
https://github.com/umputun/remark42/runs/3514335438?check_suite_focus=true#step:6:157
https://github.com/umputun/remark42/runs/3514334170?check_suite_focus=true#step:6:157

Prevent data race within TestService_UserReplies

---

backend/app/migrator/backup.go
backend/app/store/image/image.go

https://github.com/golang/go/wiki/CodeReviewConcurrency#ticker-stop

stop Ticker after use to prevent the memory leak

---

backend/app/cmd/server.go

Clarification of the code I came up with when was working on new telegram user notifications in #1160.

Clarify telegram notification flow

---

backend/app/cmd/server.go

Second part of https://github.com/umputun/remark42/pull/1160, allowing telegram auth and notify to work at the same time.

Use single loop for telegram auth and notify

---

backend/app/rest/httperrors.go

Update comment for `SendErrorJSON`

Updated comment for rest.SendErrorJSON

---

frontend/app/components/comment-form/__markdown-toolbar/comment-form__markdown-toolbar.css
frontend/app/components/select/select.module.css

PR for [#1082](https://github.com/umputun/remark42/issues/1182)
Added cursor pointer for toolbar buttons and select dropdown.

feat: add cursor pointer for buttons

---

site/src/docs/getting-started/installation/index.md

I think it'll be helpful for people directly coming to documentation.

Add link of docker-compose file

---

frontend/app/common/api.test.ts
frontend/app/common/api.ts
frontend/app/components/preloader.tsx
frontend/app/components/profile/profile.module.css
frontend/app/components/profile/profile.spec.tsx
frontend/app/components/profile/profile.tsx
frontend/app/components/spinner/spinner.module.css
frontend/app/components/spinner/spinner.tsx
frontend/app/locales/be.json
frontend/app/locales/bg.json
frontend/app/locales/bp.json
frontend/app/locales/de.json
frontend/app/locales/en.json
frontend/app/locales/es.json
frontend/app/locales/fi.json
frontend/app/locales/fr.json
frontend/app/locales/ja.json
frontend/app/locales/ko.json
frontend/app/locales/pl.json
frontend/app/locales/ru.json
frontend/app/locales/tr.json
frontend/app/locales/ua.json
frontend/app/locales/vi.json
frontend/app/locales/zh.json

Issue: https://github.com/umputun/remark42/issues/1085
**Profile sidebar with load more button**

Add Load More button to profile sidebar

---

site/.eleventy.js

Issues: https://github.com/umputun/remark42/issues/1167, https://github.com/umputun/remark42/issues/1200

Add container to a markdown table with overflow-x auto

---

site/yarn.lock

Revert "update site lockfile"

---

site/.eleventy.js
site/src/data/github.js

Update Eleventy's config after update to 1.0

Update eleventy config

---

site/src/docs/contributing/development/frontend/index.md

Fix frontend documentation typo

---

backend/_example/memory_store/go.sum
backend/go.mod
backend/go.sum
backend/vendor/github.com/go-pkgz/auth/provider/providers.go
backend/vendor/modules.txt

Follow-up for https://github.com/go-pkgz/auth/pull/107

Bump auth module

---

site/src/docs/configuration/parameters/index.md

During the work on #1254 I found two inconsistencies in our documentation.

Add proper default values for two boolean variables

---

frontend/app/components/auth/auth.tsx

Accordingly to #1276 updates QR size to 200px and make it square.

update telegram qr size

---

site/src/docs/getting-started/installation/index.md

Fixes problem highlighted in #1278 and https://github.com/umputun/remark42/issues/26#issuecomment-1026637561

Fix remark_config reference in the installation documentation

---

backend/app/cmd/backup.go
backend/app/cmd/import.go
backend/app/cmd/remap.go
backend/app/cmd/restore.go

Increase timeout for backup and restore and remap 15m->60m

---

site/src/docs/configuration/authorization/index.md

Add warning to Twitter section in docs Authorization page

---

site/src/docs/getting-started/installation/index.md

Added proper variables names and reference to the frontend configuration.

Improve getting started installation instructions

---

site/src/docs/configuration/frontend/index.md
site/src/docs/configuration/frontend/spa.md
site/src/docs/getting-started/installation/index.md
site/src/styles.css

- move all of the descriptions for FE params into text
- add notes in the necessary places

Improve frontend docs

---

frontend/.babelrc.js
frontend/package-lock.json
frontend/package.json

remove `testid` attribute from elements when build for production

clean testid in production build

---

frontend/app/components/auth/components/oauth.tsx

fix basepath for oauth icons

---

frontend/.size-limit.js
frontend/app/components/comment/connected-comment.tsx
frontend/app/components/input/input.tsx
frontend/app/components/profile/profile.tsx
frontend/app/components/root/in-view/in-view.tsx
frontend/app/components/root/root.tsx
frontend/app/components/sort-picker.tsx
frontend/app/components/textarea-autosize.tsx
frontend/app/components/thread/thread.tsx
frontend/app/store/comments/actions.ts
frontend/app/store/index.ts
frontend/app/store/theme/actions.ts
frontend/app/store/thread/actions.ts
frontend/app/store/user/actions.ts
frontend/app/typings/global.d.ts
frontend/jest.config.ts
frontend/package-lock.json
frontend/package.json

- bump prod deps
- small code adjustment for Input component
- Preact is only updated to 10.6.2 because newer version are not compatible with testing-library
- update redux types
- fix typing problems
Had to update size limit after deps update.

bump prod deps

---

Dockerfile

fix frontend test/build in docker

---

site/Dockerfile.dev
site/docker-compose.yml
site/package.json

adds ability to run site in dev mode inside docker
useful for writing and testing documentation

run dev env for site in docker

---

docker-compose.yml
site/src/docs/contributing/backend/index.md

I missed these during the original writing.

Proper grammar for ADMIN_PASSWD parameter notes

---

site/src/docs/configuration/parameters/index.md

Also, clarify the wording on TIME_ZONE parameter a little.

Remove duplicated docker-compose.yml from parameters doc

---

frontend/apps/remark42/tasks/supportedLocales.json

Update supportedLocales.json Add Thai language

---

README.md

add contribution links in readme

---

frontend/apps/remark42/app/components/auth/auth.hooks.ts
frontend/apps/remark42/app/components/root/root.tsx
frontend/apps/remark42/webpack.config.js

Revert "fix iframe resize on auth dropdown opening"

---

frontend/apps/remark42/app/common/api.ts

admin: fix block period

---

backend/app/store/engine/bolt.go
backend/app/store/image/fs_store_test.go
backend/app/store/service/service.go
site/src/docs/contributing/frontend/index.md

Fix "it's" used in place of "its"

---

Dockerfile

It should be removed after changes in 141c75401.

Remove unused entrypoint.sh

---

backend/_example/memory_store/accessor/data.go

github.com/go-pkgz/lgr should be used instead for consistency with the rest of the code

Remove the only generic logger usage

---

backend/app/rest/api/rest.go
backend/app/rest/api/rest_test.go

Addresses https://github.com/umputun/remark42/issues/1477#issuecomment-1300546219

Allow dots in site id during email user validation

---

frontend/apps/remark42/app/components/root/root.tsx

fix: update iframe size on mount

---

frontend/apps/remark42/package.json
frontend/package.json
site/src/docs/contributing/frontend/index.md

Resolves #1530
Documentation wasn't matching reality.
Updated run commands and docs.

fix: update fe contributing documentation and get dev commands in order

---

.dockerignore
Makefile

Also, add missing entries to .dockerignore.

Add e2e tests to makefile

---

frontend/apps/remark42/app/utils/loadLocale.ts

#1605 fix loading th locale

---

site/src/docs/configuration/authorization/index.md

https://remark42.com/docs/configuration/authorization/

Fixed wrong markdown at the site

---

site/src/docs/configuration/telegram/index.md

Remove outdated information about functionality which was already implemented.

Update Telegram notifications instructions

---

backend/app/rest/api/rest_public_test.go

These tests just clarify the existing behaviour so that we know what would change if we decide to introduce the change. Related to #1677.

Reproduce report of CWE-918 from #1677

---

site/src/docs/nav.json

That addresses https://github.com/umputun/remark42/issues/26#issuecomment-1724751762.

Clarify titles for frontend and backend configuration doc

---

frontend/apps/remark42/app/components/comment-form/__markdown-link/comment-form__markdown-link.css
frontend/apps/remark42/app/components/comment/_theme/_dark/comment_theme_dark.css
frontend/apps/remark42/app/components/comment/_theme/_light/comment_theme_light.css
frontend/apps/remark42/app/components/comment/comment.module.css
frontend/apps/remark42/app/components/raw-content/raw-content.css
frontend/apps/remark42/app/components/root/_theme/_dark/root_theme_dark.css
frontend/apps/remark42/app/styles/custom-properties.css
frontend/apps/remark42/app/styles/global.css

- move link style to global
- make hovers a bit darker on light theme and lighther on dark theme

update links styles

---

backend/app/store/engine/bolt.go

The new code does the same as the old one but doesn't call the checkFlag in case ReadOnly is already set based on age.

Simplify BoltDB.Info code

---

backend/app/rest/api/admin_test.go
backend/app/rest/api/rest_public_test.go
backend/app/rest/api/rest_test.go

This would be useful to reduce the scope of other upcoming changes. No logic changes were introduced; tests describe the system's current behaviour.

Add more tests for GET /find endpoint

---

site/.prettierignore
site/.prettierrc
site/Dockerfile
site/Dockerfile.dev
site/README.md
site/package.json
site/src/docs/backup/url-migration/index.md
site/src/docs/configuration/authorization/index.md
site/src/docs/configuration/email/index.md
site/src/docs/configuration/frontend/index.md
site/src/docs/configuration/frontend/spa.md
site/src/docs/configuration/parameters/index.md
site/src/docs/configuration/telegram/index.md
site/src/docs/contributing/api/index.md
site/src/docs/getting-started/installation/index.md
site/src/docs/manuals/integration-with-astro/index.md
site/src/docs/manuals/integration-with-gatsby/index.md
site/src/docs/manuals/separate-domain/index.md
site/src/docs/manuals/subdomain/index.md
site/src/docs/nav.json
site/src/includes/components/head.njk
site/src/includes/components/header.njk
site/src/layouts/base.njk
site/src/pages/index.md
site/src/pages/redirects.md
site/tailwind.config.js
site/yarn.lock

Renew the /site with up-to-date packages and apply prettier rules that were already present but not enforced before.

Update /site packages, Node version, apply prettier

---

backend/app/notify/webhook.go
backend/app/notify/webhook_test.go
site/src/docs/configuration/notifications/index.md
site/src/docs/configuration/parameters/index.md

Add escaping of comment text in webhook default JSON template

---

site/src/docs/configuration/authorization/index.md

Tested on remark42 demo to clarify what works and what doesn't. Resolves #1785.

Fix restrictions for anonymous usernames

---

Makefile
backend/_example/memory_store/README.md
compose-dev-backend.yml
compose-dev-frontend.yml
docker-compose.yml
site/README.md
site/src/docs/configuration/email/index.md
site/src/docs/contributing/backend/index.md
site/src/docs/contributing/frontend/index.md
site/src/docs/contributing/translations/index.md
site/src/docs/getting-started/installation/index.md
site/src/docs/manuals/reproxy/index.md
site/src/docs/manuals/subdomain/index.md

Compose is part of docker command for years and during local development
on Mac I have to change makefile locally for commands to work.

Update docker-compose command to docker compose
